ShuyunFF2E/cloud-react

src/components/button/index.js

`button`标签只支持`type`属性，但是由于封装过后`type`用来干别的事情了，用`htmlType`来代替原生`button`上的`type`，忘了在使用的时候把`htmlType`转成`type`了

:bug: 修复Button组件htmlType为type

---

src/components/tag/index.js

Fix(Tags) 执行删除 tag 操作时，阻止事件冒泡

---

src/components/modal/demos/info.markdown
src/components/modal/index.js
src/components/modal/index.md
src/components/modal/prompt.js

1、增加isShowIcon属性，用于是否显示提示信息前面的icon， 布尔类型，默认为true；
2、增加icon属性，用于提示自定义信息前面icon, 即icon组件中的type名称，字符串类型；
3、增加iconStyle属性，用于自定义提示信息前面icon的样式，对象类型；

:sparkles: [Modal组件]提示类型modal增加icon配置

---

src/components/input-number/index.less

- inputNumber 组件默认高度 32px，其它表单组件默认高度 30px；
- inputNumber 组件鼠标 hover 和 focus 的颜色和其它表单组件不一致；
- inputNumber 组件，focus 的时候设置了 boxshadow（看起来也很不美观），其它表单组件没有设置

:lipstick: [inputNumber] 修改默认高度和边框颜色，和其它表单组件保持一致

---

src/components/tree-select/demos/multiple.markdown
src/components/tree-select/index.js
src/components/tree-select/index.md
src/components/tree-select/tree.js

https://github.com/ShuyunFF2E/cloud-react/issues/71
1. 需要支持下拉多选
2. 下拉包裹树组件，组件内部交互以Tree为基准，onChange及带确认按钮的多选操作与Select组件基本一致，详见demo中的multiple.markdown
支持下拉多选树

:sparkles: [TreeSelect] 完善下拉多选树

---

src/components/tree-select/demos/basic.markdown
src/components/tree-select/demos/multiple.markdown
src/components/tree-select/index.js
src/components/tree-select/index.md
src/components/tree-select/selected.js
src/components/tree-select/tree.js

1.需要多层级下拉树单选
2.将Tree组件单选嵌入TreeSelect
3.添加标记single即为下拉多层单选树，和之前的multiple参数同样，设置该参数后内部逻辑除select本身的一些交互外，其余参考Tree
可使用下拉多层单选树

:sparkles: [TreeSelect] 添加多层树单选

---

src/components/input-number/index.js

https://github.com/ShuyunFF2E/cloud-react/issues/230
InputNumber组件手动输入获取的值类型为字符串
点击InputNumber旁边的上下箭头获取的值类型为数字
defaultValue设置为 '0', 输入框里未显示
1. input组件defaultValue设置为0
2. onChange返回类型

🐛 [InputNumber] issue: #2330

---

src/components/select/index.less

1. Select组件显示为块元素布局，在表单项中使用大部分情况都需要去修改成内联块的方式
1. Select组件显示为块元素布局，在表单项中使用大部分情况都需要去修改成内联块的方式
2. 仅仅修改了`display: block` => `display: inline-block`

[Select] 修改Select组件显示方式为内联块

---

src/components/modal/index.less

1. 非定制化的Modal内容部分字体大小应该集成自项目全局所设置的字体大小

[Modal] 去除弹框body容器设置的字体大小,自由的内容应继承项目设置的字体大小

---

src/components/modal/demos/style.markdown
src/components/modal/index.js
src/components/modal/index.md
src/components/modal/modal.js

在某些情况下，在进行modal内部操作时，不希望确定按钮能够点击，因此增加disabledOk属性，用于控制确定按钮能否点击；
1、增加disabledOk属性，控制确定按钮能否点击，当设置了showConfirmLoading属性为true时，会优先使用showConfirmLoading；

[Modal]增加disabledOk属性，用于禁止点击确认按钮

---

src/components/tag/index.js

1. 需要在点击行为上进行阻止事件冒泡，但是获取不到`Event`对象
1. 解决`onClick`事件获取不到`Event`对象问题
- 修复Tag组件点击行为获取不到`Event`对象bug

[Tag]修复点击事件获取不到event问题

---

src/components/field/demos/basic-forms.markdown
src/components/form/constants.js
src/components/form/explain.js
src/components/form/form-item.js
src/components/form/index.js
src/components/form/index.less
src/components/form/index.md
src/components/form/nexus.js

1. Form.Item组件内容如果是抽离组件的话，Field注册的校验就没法触发页面的渲染，因为Form.Item无法窥视被抽离组件内部存在的内容
1. 解决复杂表单场景下嵌套独立组件内部存在表单校验行为时无法处理错误等相关提示问题
1. 修复复杂表单场景下嵌套独立组件内部存在表单校验行为时无法处理错误等相关提示问题

[Form] 新增独立组件内部使用Field.init注册表单连接器

---

src/components/tree/index.js
src/components/tree/store.js

1、设置了isUnfold属性，但是一直都处于闭合状态，bug，取值错误，导致出现undefined；
2、选中过节点后，再切换回显数据，选中项状态未改变，节点选中状态没有清除，已统一初始化数据清除选中状态；
1、修复选中数据后回显数据变化但是选中节点状态未变化bug；
2、修复设置isUnfold为true后选择节点但又闭合的bug；

[Tree]修复选中节点后切换回显数据选中节点状态未变化问题

---

src/components/tree/demos/showIcon.markdown
src/components/tree/index.js
src/components/tree/index.md
src/components/tree/store.js

1、根据UI建议，默认不展示节点前面的图标；
2、当传入的treeData为空或不存在时，组件报错；
1、设置showIcon的默认值为false，默认不展示节点前面的小图标；
2、兼容treeData为空或不存在情况时，显示无结果提示；

[Tree]默认不展示节点前面的图标, 兼容无数据状态

---

src/components/tree/demos/changeSelectedValue.markdown
src/components/tree/index.md
src/components/tree/store.js

某些情况下，节点的id或者pId为0，导致在组件内部进行判断时出现判断错误情况，进而致使节点选择或回显等功能收到影响；
增加判断是否为0的判断条件进行兼容；
1、清除使用parentId的方式设置父节点id；
2、兼容节点id或pId为0情况；

:bug:[Tree]修复节点id或pId为0的时选择或回显状态错乱问题

---

src/components/field/index.js
src/components/form/constants.js
src/components/form/form-item.js

`Form.Item`组件内容中注册的表单校验规则在内容销毁时没有相应的销毁注册在Field工具中的信息
1. `Form.Item`组件内容中注册的表单校验规则在内容销毁时没有相应的销毁注册在Field工具中的信息。
2. 通过监测内容发生变化找出本次变更中已经不存在的字段名并在Field工具中销毁
新增`Form.Item`组件对其children内容变化后找出之前注册过且当前变更后不存在的表单字段进行销毁

[Form.Item]组件新增内容销毁时同时销毁已经注册的Field字段

---

src/components/input/index.less

input元素部分样式被项目的全局样式覆盖
input元素部分样式被项目的全局样式覆盖
修复Input组件中的input元素部分样式被项目的全局样式覆盖问题

[Input] 原生input元素部分样式添加!important标识,避免被全局样式所影响

---

src/components/modal/index.js
src/components/modal/index.md

https://github.com/ShuyunFF2E/cloud-react/issues/274
1. 修复Modal默认挂载父级，新增用户可指定挂载父级
修复Modal默认挂载父级，同时新增用户可指定挂载父级API

[Modal]新增getPopupContainer方法允许用户自己指定节点渲染父级

---

src/components/field/demos/basic-forms.markdown
src/components/field/index.js
src/components/field/index.md

https://github.com/ShuyunFF2E/cloud-react/issues/285
1. 可选择性临时关闭某个字段的校验行为
2. `Field.prototype.init(name, [opts])`可选参数新增`checkable`字段
`Field.prototype.init(name, [opts])`可选参数新增`checkable`字段，可临时开启/关闭某个字段的校验行为

[Field] init方法可选参数新增checkable字段

---

src/components/form/form-item.js
src/components/form/form-nexus.js
src/components/form/index.js
src/components/form/render-children.js

无相关issue
1. 存在多个相同的方法
1. 减少`Form.Item`和`Form.Nexus`的冗余代码

[Form] 合并Form.Item和Form.Nexus渲染内容部分代码

---

src/components/modal/demos/iframe.markdown
src/components/modal/index.js
src/components/modal/index.less
src/components/modal/modal.js
src/components/modal/prompt.js
src/utils/get-root-document.js
src/utils/index.js

当项目在被嵌套在一个iframe框架中的时候，弹框无法挂载到相同域上的父窗口问题
1. 当使用弹框的项目被嵌套在iframe窗口时，弹框不能全屏显示
2. 无API变更，在组件内部挂载之前查到了可挂载的顶层父窗口
新增`Modal`组件在iframe嵌套时可智能挂载到所能访问的最高层级父窗口
修复`Modal`组件在拖拽时会存在选中页面文字bug
修复`Modal`跨iframe交互时动画效果卡顿bug

[Modal]新增iframe嵌套时且在不跨域的情况将Modal挂载到可访问最高层窗口的body节点上

---

src/components/modal/demos/nest.markdown
src/components/modal/index.js
src/components/modal/index.md
src/components/modal/modal.js
src/components/modal/prompt.js
src/utils/get-root-document.js

-   [x] 新特性提交
新增参数让开发者可选择是否要将Modal组件挂载到iframe（如果有的话）之外的父窗口上
新增Modal组件是否可以挂载到iframe的顶层窗口

[Modal]修改弹框组件使用时可选择是否挂载到iframe之外的顶层父级

---

src/components/tree/index.js
src/components/tree/store.js

-   [ ] 新特性提交
-   [ ] 组件样式改进
-   [ ] 重构
-   [ ] 代码风格优化
原来的代码中 treeData 和 allTreeData 分别用来渲染树和作为搜索树的数据源。在搜索后的基础上进行添加/编辑/删除目录操作，这个时候会同时更新 treeData 和 allTreeData，更新数据的数据源是经过筛选的 treeData(不是完整的treeData)，因此导致 allTreeData 不是都有的数据了，再次进行搜索的时候，就会出问题。

:bug: [Tree] 输入关键字搜索，新增目录，清除搜索内容重新搜索，结果错误

---

src/components/form/index.js

使用对浏览器版本过高的特性导致低版本浏览器不支持报错问题
1. 使用对浏览器版本过高的特性导致低版本浏览器不支持报错问题
2. 改用通用的特性
修复Form组件使用了Object.values方法导致低版本浏览器不支持bug

:bug:[Form]修复组件内部使用了Object.values低版本浏览器不支持问题

---

src/components/modal/modal.js

[Modal] 异步加载高度变化重新定位

---

src/components/field/index.js

`field.prototype.reset`、`field.prototype.clear`、`field.prototype.remove` 调用时没有清除`__fieldsMeta__`对象中的值导致部分场景下会出现设置的值清不掉bug
1. `field.prototype.reset`、`field.prototype.clear`、`field.prototype.remove` 调用时没有清除`__fieldsMeta__`对象中的值导致部分场景下会出现设置的值清不掉bug
2. 在调用这些方法后执行`delete this.__fieldsMeta__[name]`
修复`field.prototype.reset`、`field.prototype.clear`、`field.prototype.remove`方法没有及时清理临时存储对象bug

[Field] 修复field.(clear|reset|remove)调用后没有处理存储在__fieldsMeta__对象中的值问题

---

src/components/tree-select/demos/multiple.markdown
src/components/tree-select/index.less
src/components/tree/demos/defineStyle.markdown
src/components/tree/index.js
src/components/tree/index.less
src/components/tree/menu.js
src/components/tree/node.js
src/components/tree/store.js

这个变动的性质是？
-   [ ] 新功能提交
-   [ ] 组件样式改进
-   [ ] 代码风格优化
-   [ ] 重构
1. Tree：当横向出现滚动条，选中目录后，背景色区域右侧留白过多；
2. Tree：当横向出现滚动条，hover不同层级的目录，背景色宽度不一样
3. Tree：右键新增或者编辑的时候，输入框自动滚动到可视区域（线上问题）
4. Tree：点击保存和取消按钮的时候，阻止事件冒泡；
5. Tree：调整不同层级的缩进和一个字的大小相等，否则带有子节点和不带子节点目录会对不齐，大约会差2px；
6. Tree：存在多个根节点的情况处理（涉及多选Tree相关逻辑）
7. Tree：监听外部回显数据变化的时候，传入的 treeData 应为 state 中保存的数据，而不是从 pros 中拿的原数据（造成的问题：在多选下拉组件中使用的时候，如果把tree展开或者折叠后再选中，状态会恢复成原始状态）

:art: [Tree][TreeSelect] 样式和交互优化

---

src/components/field/index.js
src/components/form/constants.js
src/components/form/demos/basic-usage.markdown
src/components/form/index.js
src/components/form/index.md

-   [x] 新功能提交
1. 表单容器较小时，失败的表单项如果不在可视区域，可将其滚动至可视区域
2. `Form`组件新增`scrollToFirstError`字段，值为`true/false`默认为`false`
1. `Form`组件新增表单校验失败时可将不在可视区域的第一条失败的内容展示到可视区域内，使用`scrollToFirstError`字段来选择是否开启

[Form] 新增表单提交失败时可让失败的第一个表单项滚动至可视区域特性

---

src/components/datepicker/common/picker.js
src/components/modal/config-provider.js
src/components/modal/constants.js
src/components/modal/index.js
src/components/modal/modal.js
src/components/select/index.js
src/components/tooltip/index.js

1. iframe场景下Modal组件创建到顶层文档时会创建隔离容器，但其他普通组件直接创建到body了，样式有可能会存在丢失
2. Modal.ConfigProvider 提供 getContext方法可获取隔离容器
1. 修复Modal组件在iframe场景下内容可能会出现样式丢失问题

[Modal]修复弹框组件在iframe场景下基础组件不在隔离容器内问题

---

src/components/tooltip/toolView.js

1. Tooltip组件content属性的值为数组类型的JSX时，渲染错误问题
2. 修改ReactNode和HTML格式判断逻辑
1. 修复Tooltip组件content属性渲染数组结构JSX节点异常bug

[Tooltip]修复content值渲染方式异常问题

---

src/components/tree/demos/defineIcon.markdown
src/components/tree/demos/defineStyle.markdown
src/components/tree/demos/drag.markdown
src/components/tree/demos/menuDialog.markdown
src/components/tree/index.js
src/components/tree/index.less
src/components/tree/index.md
src/components/tree/list.js
src/components/tree/menu.js
src/components/tree/node.js
src/components/tree/store.js

-   [X] 新功能提交
-   [ ] 组件样式改进
-   [ ] 代码风格优化
-   [ ] 重构
1、解决某些场景中需要拖拽节点换位，增加supportDrag属性控制是否使用拖拽功能；增加onDragBefore、onDrag、onDragAfter用于拖拽前、拖拽中、拖拽后事件回调；
2、增加双击节点事件；使用onDoubleClick触发双击节点事件；
3、增加弹框类型菜单；使用menuType进行菜单类型控制，可使用弹框形式与行内形式修改或 新建节点；
4、增加isShowNameTooltip用于控制是否显示节点 tooltip，因为要使用固定宽度的树且最多展示两行时，需要tootip；

[Tree]增加拖拽功能,增加弹框形式菜单,增加双击事件

---

src/components/message/index.js

-   [ ] 新功能提交
-   [ ] 组件样式改进
-   [ ] 代码风格优化
-   [ ] 重构
1. `Message`组件在`iframe`嵌套场景下偶尔获取不到顶层`window`全局对象
2. 通过排查是获取时机不对，之前是在初始化时就进行获取了，目前改成使用时再获取
修复`Message`组件获取顶层`window`全局对象时机不正确bug

[Message]修复组件获取rootWindow时机不对问题

---

src/components/tree/demos/defineStyle.markdown
src/components/tree/demos/menuDialog.markdown
src/components/tree/index.js
src/components/tree/index.less
src/components/tree/index.md
src/components/tree/node.js

-   [ ] 新功能提交
-   [X] 组件样式改进
-   [ ] 代码风格优化
-   [ ] 重构
1、由上个版本中单个节点最多显示两行跳整为显示一行；
2、设置固定宽度后，如果节点长度超过计算的宽度则显示tooltip；
1、节点调整为单行显示，超过指定宽度显示...，鼠标悬浮显示完整节点名称；
2、节点被选中后，鼠标悬浮则背景色显示选中的背景色；

[Tree]样式调整优化

---

src/components/form/index.less

-   [ ] 新功能提交
-   [x] 组件样式改进
-   [ ] 代码风格优化
-   [ ] 重构
1. Form表单中表单项校验状态的样式影响了日期组件内部下拉框的样式
2. 通过更精准的CSS选择器匹配规则查找元素
修复`Form`表单中表单项校验状态的样式影响了日期组件内部下拉框的样式

[Form]修复表单项校验状态的日期组件内部下拉框样式会受到影响bug

---

src/components/tree-select/tree.js
src/components/tree/index.js

-   [ ] 新功能提交
-   [ ] 组件样式改进
-   [ ] 代码风格优化
-   [ ] 重构
tree组件中当数据源为空时dom节点不渲染导致使用ref报错；
1、修复tree组件中数据为空时获取ref报错问题；
2、优化tree-select组件中数据为空的显示方式；

:bug: [tree][tree-select] 修复tree组件中数据为空时ref报错问题

---

src/components/tree-select/demos/multiple.markdown
src/components/tree/demos/basicSelector.markdown
src/components/tree/demos/multipleSelect.markdown
src/components/tree/index.js
src/components/tree/index.less
src/components/tree/search.js
src/components/tree/store.js

-   [x] 新功能提交
-   [ ] 组件样式改进
-   [ ] 代码风格优化
-   [ ] 重构
背景：商品选择器中的自定义类目和标准类目下拉树多选框增加模糊搜索功能
解决方案：树组件在多选的情况下增加模糊搜索功能

[tree]增加多选可筛选功能

---

src/utils/get-styles.js

-   [ ] 新功能提交
-   [ ] 组件样式改进
-   [ ] 代码风格优化
-   [ ] 重构
获取页面样式表规则碰到跨域样式表出现不允许访问错误
修复获取样式表规则时碰到跨域样式表直接报错问题

:bug:[Modal]修复获取样式表规则时碰到跨域样式表直接报错问题

---

src/components/datepicker/common/picker.js
src/components/datepicker/common/time.js
src/components/datepicker/constant.js
src/components/datepicker/date-picker/grid.js
src/components/datepicker/date-picker/index.js
src/components/datepicker/date-picker/main.js
src/components/datepicker/date-range/index.js
src/components/datepicker/demos/date-picker.markdown
src/components/datepicker/demos/disabled.markdown
src/components/datepicker/demos/modal.markdown
src/components/datepicker/demos/month-day-picker.markdown
src/components/datepicker/demos/range-date-picker.markdown
src/components/datepicker/demos/time-picker.markdown
src/components/datepicker/demos/year-month-picker.markdown
src/components/datepicker/demos/year-picker.markdown
src/components/datepicker/index.md
src/components/datepicker/month-day/index.js
src/components/datepicker/month-day/main.js
src/components/datepicker/proptypes.js
src/components/datepicker/utils.js
src/components/datepicker/year-month/grid.js
src/components/datepicker/year-month/index.js
src/components/datepicker/year-month/main.js
src/components/datepicker/year/grid.js
src/components/datepicker/year/index.js
src/components/datepicker/year/main.js
src/components/field/demos/test-date.markdown

-   [x] 新功能提交
-   [ ] 组件样式改进
-   [ ] 代码风格优化
-   [ ] 重构
需求背景：日历组件增加手动输入功能，更方便用户使用
解决方案
- 增加是否支持可输入配置字段，默认不可输入
- 手动输入的日期格式正确时，日历联动选中
- 手动输入的日期格式错误时，日历不联动选中（特殊情况：年月日 时分秒，当年月日格式正确时，日历会联动选中年月日）
- 可编辑的状态下，增加回车事件、失去焦点事件，将输入的日期抛出给业务端

[datepicker]支持手动输入时间

---

src/components/modal/modal.js

-   [ ] 新功能提交
-   [ ] 组件样式改进
-   [ ] 代码风格优化
-   [ ] 重构

修复iframe下使用弹窗，会在父窗口head遗留style 影响其余样式

---

src/components/upload/demos/before-confirm.md
src/components/upload/demos/before-upload.md
src/components/upload/demos/custom-request.md
src/components/upload/demos/custom-upload.md
src/components/upload/demos/file-list-picture.md
src/components/upload/demos/file-list-text.md
src/components/upload/demos/picture.md
src/components/upload/index.js
src/components/upload/index.less
src/components/upload/index.md
src/components/upload/list.js

-   [ ] 新功能提交
-   [ ] 组件样式改进
1.ui优化
2.onBeforeUpload新增支持异步函数
3.组件内部支持判断可选文件类型
1.onBeforeUpload新增支持异步函数
2.新增普通文件上传显示类型图标
3.组件内部支持判断可选文件类型
4.部分ui优化
-   [ ] 文档已补充

[Upload] 普通文件上传显示类型图标/onBeforeUpload支持异步函数/组件内部支持判断可选文件类型/ui优化

---

src/components/c-table/index.js

-   [X] 新功能提交
-   [ ] bugfix
-   [ ] 组件样式改进
-   [ ] 代码风格优化
-   [ ] 重构

feat: [CTable] 支持受控分页，多用于表格记忆功能

---

src/components/c-picker/demos/range-picker.md
src/components/c-picker/pickers/date-range.js

-   [ ] 新功能提交
-   [ ] bugfix
-   [x] 组件样式改进
-   [ ] 代码风格优化
-   [ ] 重构

fix: [CPicker] 区间单侧时间禁用时，选择另一侧后直接关闭面板
