ShuyunFF2E/cloud-react

src/components/button/demos/basic.markdown, src/components/button/demos/block.markdown, src/components/button/demos/disabled.markdown, src/components/button/demos/group.markdown, src/components/button/demos/size.markdown, src/components/button/index.js, src/components/button/index.less, src/components/button/index.md
1. 完成Button组件功能
2. 完成Button组件API文档
3. 完成Button组件Demo文档
=> :sparkles: :memo: add button component & demo

scripts/loaders/dynamic-docs-loader.js
=> dynamic-doc-loader 兼容win

src/components/tabs/index.js
=> feat: Tab组件支持className属性定义根结点样式

src/components/tabs/index.js, src/components/tabs/index.md
=> Tabs组件添加新特性

src/components/menu/menu-item.js
=> Menu组件问题修复

src/components/tabs/index.js, src/components/tabs/index.md
=> 优化Tabs组件表现形式

src/components/index.js, src/components/tag/demos/basic.markdown, src/components/tag/demos/categories.markdown, src/components/tag/demos/state.markdown, src/components/tag/index.js, src/components/tag/index.less, src/components/tag/index.md
=> develop tag component

src/components/tooltip/config.js, src/components/tooltip/demos/basic.markdown, src/components/tooltip/demos/control.markdown, src/components/tooltip/demos/placement.markdown, src/components/tooltip/index.js, src/components/tooltip/index.less, src/components/tooltip/index.md, src/components/tooltip/toolView.js
1.新增visible跟container两个api
2.对之前代码优化
=> tooltip新增两个API,手动控制tooltip显示和指定tooltip渲染节点,并对之前代码优化

src/components/modal/demos/confirm.markdown, src/components/modal/demos/conplex.markdown, src/components/modal/demos/info.markdown, src/components/modal/demos/nest.markdown, src/components/modal/demos/style.markdown, src/components/modal/index.js, src/components/modal/index.less, src/components/modal/index.md, src/components/modal/modal.js, src/components/modal/prompt.js
1、修复文字虚化问题；
2、增加style属性，可自定义modal-body样式；
3、删除confirm弹框中titlte属性；
4、修复弹窗中嵌套弹窗时遮罩层重复问题；
5、开启默认点击遮罩层关闭弹窗；
=> [Feature]modal组件优化

package.json, src/components/table/demos/static.markdown
- 表格组件版本更新至：0.3.2
- 表格组件静态数据Demo更新
=> 更新表格组件版本及demo

src/components/tree/index.js, src/components/tree/index.less, src/components/tree/menu.js, src/components/tree/node.js
1、调整tree组件样式；
2、修复tree组件demo中删除时提示框内容无效问题（modal组件调整导致）；
=> feature:调整tree组件样式

src/components/field/index.js, src/components/form/form-item.js, src/components/form/index.less
`field.setValue`在`field.init`之前执行引发的校验异常问题已修https://github.com/ShuyunFF2E/cloud-react/issues/87
=> form-item组件的cihldren支持普通标签包裹校验类型组件,同时支持多个兄弟级的校验类型组件

src/components/tree/index.js
修复树组件中存在删除存在子节点的节点时不成功但是提示删除成功的bug
=> fixBug： tree

src/components/tooltip/demos/basic.markdown, src/components/tooltip/index.js
=> tooltip 问题修改 实现方式优化

src/components/modal/demos/component.markdown, src/components/modal/demos/conplex.markdown, src/components/modal/demos/style.markdown, src/components/modal/index.js, src/components/modal/index.less, src/components/modal/index.md, src/components/modal/modal.js, src/components/modal/prompt.js, src/components/style/core/zindex.less
1、优化结合其他组件使用时部分样式问题；
2、增加modalStyle与bodyStyle属性，用于用户自定义modal样式；
3、删除冗余代码，提高代码简洁性；
4、增加modal使用其他组件demo；
=> feature:优化modal组件

src/components/datepicker/index.less, src/components/message/index.less, src/components/modal/index.less, src/components/radio/index.less, src/components/select/index.js, src/components/select/index.less, src/components/style/core/zindex.less, src/components/tooltip/index.less
```less
@z-index-dropdown: 1000; // select 下拉
@z-index-modal: 1010; // modal 弹窗
@z-index-modal-mask: 1010; // modal 弹窗遮罩
@z-index-picker: 1010; // 时间选择器弹窗
@z-index-message: 1020; // Message 提示
@z-index-tooltip: 1030; // tooltip 提示
```
=> :art: 组件的 z-index 统一管理

src/components/datepicker/date-picker/index.js, src/components/datepicker/month-day-picker/index.js, src/components/datepicker/range-picker/index.js, src/components/datepicker/time-picker/index.js, src/components/datepicker/year-month-picker/index.js, src/components/datepicker/year-picker/index.js
=> 🐛 [DatePicker组件] 解决Datepicker value绑定问题

src/components/input/index.js
1. 复现demo
````javascript
import React from 'react';
import { Input, Icon, Table } from 'cloud-react';
const resource = fetch('https://www.lovejavascript.com/learnLinkManager/getLearnLinkList').then(res => res.json());
const columnData = [
{
key: 'name',
text: '名称',
align: 'left'
},
{
key: 'info',
text: '使用说明'
}
];
export default function InputDemo() {
return (
<div className="input-demo-box">
<Input hasCounter maxLength="20" size="default" placeholder="单独的计数器" />
<br />
<Input hasClear hasCounter maxLength="10" size="default" placeholder="计数器加清除" />
<br />
<Input
hasCounter
maxLength="10"
hasClear
size="default"
addonBefore={<span>http://</span>}
addonAfter=".com"
placeholder="带图标"/>
<Table
gridManagerName="test-table"
ajaxData={resource}
columnData={columnData}
/>
</div>
);
}
````
2. …
=> :bug: [Input]  设置 hasCounter 为 true，并且使用表格组件，计数器渲染不完整

src/components/modal/index.less, src/components/modal/modal.js, src/components/tree/demos/defineIcon.markdown, src/components/tree/demos/immediatelySearch.markdown, src/components/tree/demos/multipleSelectedValue.markdown, src/components/tree/demos/radio_search_menu.markdown, src/components/tree/demos/selectedValue.markdown, src/components/tree/demos/showIcon.markdown, src/components/tree/index.js, src/components/tree/index.less, src/components/tree/index.md, src/components/tree/node.js, src/components/tree/search.js, src/components/tree/store.js
1、调整modal居中问题，采用动态计算方式进行垂直居中；
2、增加按住header区域可拖动弹框位置功能；
3、修复设置hasFooter后无效问题
=> 【modal组件】优化与增加新功能

src/components/tree/demos/defineStyle.markdown, src/components/tree/index.js, src/components/tree/index.md, src/components/tree/store.js
1、增加selectedValue字段用于数据回显，仅支持多选类型；
2、支持自定义节点前面的icon类型与颜色；
3、调整节点hover样式；
4、支持使用className或style属性进行自定义树样式；
5、支持使用showIcon属性控制节点前icon显示与隐藏；
6、支持使用supportImmediatelySearch属性控制是否可以实时搜索；
7、增加onSearchNode搜索回调，返回搜索值与搜索结果；
8、树的数据属性增加disableSelected属性，用于是否禁止选择节点；
=> 【tree组件】增加新功能

src/components/input-number/demos/precision.markdown, src/components/input-number/index.js, src/components/input-number/util.js
issue: https://github.com/ShuyunFF2E/cloud-react/issues/151
=> 🐛 [InputNumber组件] 受控组件错误

src/components/tree/context.js, src/components/tree/demos/defineStyle.markdown, src/components/tree/demos/radio_search_menu.markdown, src/components/tree/demos/selectedValue.markdown, src/components/tree/index.js, src/components/tree/index.less, src/components/tree/index.md, src/components/tree/node.js
1、去除radio组件方式单选，统一使用supportCheckbox属性控制单选与多选，默认单选；
2、调整tree-list最小宽度，解决在windows系统中出现多个滚动条样式问题；
=> [tree组件]:功能优化，样式调整

src/components/datepicker/date-picker/grid.js, src/components/datepicker/date-picker/index.js, src/components/datepicker/date-picker/popup.js, src/components/datepicker/index.less, src/components/datepicker/index.md, src/components/datepicker/time-picker/index.js
1. 增加Datepicker中TimePicker默认打开显示时间
2. 修复TimePicker组件defaultValue问题
3. 安标准版设计稿修改TimePicker组件部分样式
=> 修改TimePicker系列问题

src/components/modal/demos/defineInfoStyle.markdown, src/components/modal/index.less, src/components/modal/index.md, src/components/modal/prompt.js
style功能同modal中的modalStyle，用于设置整个弹出框样式
=> [modal组件]:新增style属性用于自定义提示框样式

src/components/datepicker/date-picker/index.js, src/components/datepicker/index.less, src/components/datepicker/index.md
https://github.com/ShuyunFF2E/cloud-react/issues/206
1. 解决DatePicker 输入框样式
2. 解决TImerPicker背景色继承问题
无，主要为样式修改
=> 🐛[Datepicker组件] issue #206 DatePicker样式修复

src/components/select/index.js, src/components/select/index.md
=> :sparkles: [Select] onBeforeChange添加选中值参数/值不变不触发onChange、onBeforeChange

src/components/select/demos/customConfirmBtn.markdown, src/components/select/index.js, src/components/select/index.md, src/components/select/views/multi-select.js
多选下拉可自定义配置确认取消按钮模板 confirmTemplate。
```javascript
const confirmTemplate = ({ onOk, onCancel }) => (
<div className="cloud-select-operate-btn">
<Button type="primary" size="small" disabled={disabled} className="btn" onClick={onOk} style={{ width: 92 }}>
自定义确认
</Button>
</div>
);
```
=> :sparkles: [Select] 多选下拉可自定义配置确认取消按钮模板

src/components/field/index.js
=> :sparkles: [field] validate 函数返回错误信息数组

src/components/modal/demos/basic.markdown, src/components/modal/index.less, src/components/modal/modal.js
1、项目使用出现的bug，不影响功能使用，但是需要优化；
2、项目存在使用场景，需要增加新功能以适应；
1、modal组件不显示遮罩时，可操作modal外部区域；
2、修复未自定义className名称时显示undefined；
=> :sparkles:[Modal]优化功能，修复bug

src/components/modal/index.less
1. Modal组件body容器设置了`height`、`padding`，`box-sizing`没设置（浏览器默认行为是content-box），但是项目上大部分情况都是对所有元素进行了统一设置，如：`box-sizing: border-box`，这样会导致组件的预想情况和真实情况不一致
2. 本次改动只是固定了该容器的盒模型计算方式
1. 修复modal组件在真实场景使用有可能被项目设置的`box-sizing`属性影响的问题
=> [Modal] 修复Modal组件body内容部分高度受外界影响问题

src/components/radio/index.less
1. 项目使用的时候会有可能出现额外的高度，无法重置
1. 解决在flex布局下有可能出现的额外高度问题
2. 本次改动不影响已经使用的场景
1. 适配各种场景下的布局，本次改动不影响已经使用的场景
=> [Radio] 调整radio组件内部input[type="radio"]的隐藏方式

src/components/tree-select/index.less
=> :lipstick: [TreeSelect] Form中多选下拉树行高

src/components/tree-select/demos/multiple.markdown, src/components/tree-select/index.js, src/components/tree-select/index.md, src/components/tree-select/single-tree.js, src/components/tree-select/tree.js
=> :sparkles: [TreeSelect] 添加dropdownStyle及dropdownClassName

src/components/tree/demos/basicSelector.markdown, src/components/tree/demos/multipleSelectedValue.markdown, src/components/tree/index.js, src/components/tree/index.less, src/components/tree/index.md, src/components/tree/menu.js, src/components/tree/node.js, src/components/tree/store.js
https://github.com/ShuyunFF2E/cloud-react/issues/231
1、解决多选类型数据回显bug，具体问题见 https://github.com/ShuyunFF2E/cloud-react/issues/231 ；
2、增加isUnfold属性；
3、优化节点样式；
原始：
优化后：
4、修复其他已知bug；
5、调整代码风格；
1、优化回显功能，回显节点中如果有子节点，则子节点全部选中；回显了所有的子节点，则父节点选中；
2、增加属性isUnfold，用于控制节点展开/隐藏，默认隐藏节点，根节点默认展开；
3、增加添加或重命名节点时名称重复校验；
4、调整样式，对齐同级节点，将展开/折叠的图标提前；
5、修复如果存在选中节点，但点击该节点后变为半选状态的bug；
6、修复未设置搜索回调函数时使用搜索功能导致控制台报错问题；
=> [Tree]修复已知bug，优化样式，增加新属性

src/components/tree/index.less
1、设置tree-list区域背景样式时，位置发生偏移导致样式错乱；
1、调整tree-list区域样式，解决区域位置偏移问题；
2、调整新建、重命名输入框位置，对齐父级或兄弟级；
=> [Tree]调整节点UI样式，解决位置偏移问题，优化重命名功能

src/components/field/demos/basic-forms.markdown, src/components/field/index.js, src/components/field/index.md
=> :sparkles: [Field] 添加clear清空方法

src/components/input-number/index.js
https://github.com/ShuyunFF2E/cloud-react/issues/234
1.Field中使用InputNumber组件，initValue不生效
=> fix:1.#234 initValue没有正确初始化值 2.defaultValue置空

src/components/datepicker/date-picker/index.js
https://github.com/ShuyunFF2E/cloud-react/issues/240
1. DatePicker 组件清空按钮和日历按钮没有对齐
1.DatePicker再field中使用
=> 🐛 [Datepicker] issue#240,修复field内部datepicker组件ico

src/components/radio/index.less
http://jira.yunat.com/browse/CROWD-1320
=> :art: [Radio] 修改 Radio 禁用状态颜色

src/components/select/demos/multiple.markdown, src/components/select/index.less, src/components/select/views/multi-select.js
http://jira.yunat.com/browse/CROWD-1355
=> :art: [Select] 带确定带多选下拉组件，修改滚动样式

src/components/checkbox/index.js, src/components/checkbox/index.less, src/components/select/demos/multiple.markdown
=> :lipstick: [Checkbox] 修改Checkbox选项样式

src/components/datepicker/common/header.js
https://github.com/ShuyunFF2E/cloud-react/issues/248
fix: Datepicker最大最小年份限制
=> 🐛 [Datepicker] issue - #248 修复最大最小年份问题

src/components/select/views/single-select.js
=> :art: [select] 修改单选下拉样式（超长显示滚动条）

src/components/checkbox/index.less, src/components/select/index.less, src/components/select/views/single-select.js
=> :bug: [Checkbox/Select] 修复Checkbox样式，修复Select自动定位到已选

src/components/checkbox/index.js, src/components/checkbox/index.less, src/components/select/demos/multiple.markdown, src/components/select/index.less, src/components/select/views/option.js
=> :sparkles: [Select] 修改多选下拉框内显示方式

src/components/datepicker/date-picker/popup.js, src/components/datepicker/demos/date-picker.markdown
https://github.com/ShuyunFF2E/cloud-react/issues/248
1. 先maxDate 后maxYear
2. 增加maxYear 判断
=> 🐛 [Datepicker] fix 年份超出可选问题

package-lock.json, package.json
无
无
- 表格组件优化: 减少代码构建体积，简化调用逻辑
- 表格组件修复: 开启列移动功能时，快速点击thead区域时表头会出现闪动BUG。
=> 表格组件修复拖拽bug及部分代码优化

src/components/tree-select/demos/multiple.markdown, src/components/tree-select/index.js, src/components/tree-select/index.md, src/components/tree-select/tree.js
1.添加重置功能/添加选出的值是否包含父节点
2.通过配置footerTypes类型/通过配置containParentNode
=> :sparkles: [TreeSelect] 添加footer按钮配置/添加重置按钮/添加是否所选节点包含父节点

src/components/select/index.js, src/components/select/views/selected.js
=> :sparkles: [Select] 完善hover触发的下拉框交互

src/components/datepicker/index.less
=> 💄  [Datepicker] 1.popup位置偏移问题 2.input背景色继承问题

src/components/datepicker/index.less
=> :bug: [Datepicker] 显示input添加高度

src/components/input/index.js
`onBlur`事件失效bug
1. 定义的`onBlur`事件失效了
修复`Input`组件`onBlur`事件失效bug
- [x 代码演示已提供或无须提供
=> [Input] 修复onBlur事件失效bug

src/components/select/index.js, src/components/tree-select/demos/basic.markdown, src/components/tree-select/demos/multiple.markdown, src/components/tree-select/index.js
=> :bug: [Select/TreeSelect] clear时触发onChange

src/components/button/index.less, src/components/checkbox/index.less, src/components/datepicker/index.less, src/components/form/index.less, src/components/input/index.less, src/components/loading/index.less, src/components/menu/index.less, src/components/radio/index.less, src/components/select/index.less, src/components/step/index.less, src/components/style/core/color.less, src/components/table/index.less, src/components/tabs/index.less, src/components/tag/index.less, src/components/tree-select/index.less, src/components/tree/index.less
=> :lipstick: 提取公共色值

src/components/input/index.less, src/components/tree/demos/basicSelector.markdown, src/components/tree/demos/immediatelySearch.markdown, src/components/tree/index.js, src/components/tree/node.js, src/components/tree/search.js, src/components/tree/store.js
https://github.com/ShuyunFF2E/cloud-react/issues/283
=> :bug: [Tree] 搜索、渲染相关问题修复

package-lock.json, package.json, src/components/table/demos/static.markdown, src/components/table/index.less
无
解决每个表格都需要将align调整为left的不便
表格组件列配置的align默认调整为left
=> 修改表格组件th默认值

src/components/form/render-children.js
优化获取field对象方式
优化获取field对象方式，避免通过props传递过多性能出现问题
=> 调整render-children组件获取field对象方式

src/components/tabs/index.js
=> :bug: [Tabs] tab 设置 mode="remain" 时报错

src/components/input-number/index.js, src/components/input-number/old.js, src/components/input-number/util.js
=> 重构InputNumber组件

src/components/datepicker/date-picker/index.js, src/components/datepicker/demos/range-picker.markdown, src/components/datepicker/index.md, src/components/datepicker/range-picker/grid.js, src/components/datepicker/range-picker/index.js, src/components/datepicker/range-picker/inner-time-picker.js, src/components/datepicker/range-picker/popup.js, src/components/datepicker/util/index.js
=> Datepicker增加timepicker

src/components/modal/modal.js
-   [ ] 新特性提交
-   [ ] 组件样式改进
-   [ ] 重构
-   [ ] 代码风格优化
=> :bug: [Modal] 拖动modal后，点击确定按钮，如果不关闭弹窗，弹窗位置异常

src/components/input-number/index.js, src/components/input-number/util.js
-   [ ] 新特性提交
-   [ ] 组件样式改进
-   [ ] 重构
-   [ ] 代码风格优化
=> :bug: [InputNumber] 无法输入 0.0x 0.00x

package.json
-   [ ] 新特性提交
-   [ ] 组件样式改进
-   [ ] 重构
-   [ ] 代码风格优化
升级grid-manager表格组件
=> :arrow_up: 升级gridmanager-react@0.4.5

src/utils/omit.js
修复工具omit方法使用过新的特性导致低版本浏览器报错问题
1. 修复工具omit方法使用过新的特性导致低版本浏览器报错问题
2. 降低API兼容低版本浏览器支持程度
修复工具omit方法使用过新的特性导致低版本浏览器报错问题
=> 修复工具omit方法使用过新的特性导致低版本浏览器报错问题

src/components/input/index.less
-   [ ] 组件样式改进
删除了input的宽度、高度样式上的important属性
-   [ ] 文档无须补充
-   [ ] 代码演示无须提供
=> :lipstick: [Input] 删除input宽度、高度important样式

src/components/input-number/index.js, src/components/input-number/old.js, src/components/input-number/util.js
-   [x] 组件样式改进
解决hooks写法不成熟带来的各种问题
-   [x] 文档无须补充
=> [InputNumber] refactor to class component

src/components/tree/index.js, src/components/tree/store.js
=> 【tree】输入关键字搜索，新增目录，清除搜索内容重新搜索，结果错误

src/components/input-number/index.js, src/components/input-number/util.js
=> [InputNumber] 无法输入 0.0x 0.00x 

src/components/form/index.js
-   [ ] 新特性提交
-   [ ] 组件样式改进
-   [ ] 重构
-   [ ] 代码风格优化
=> [Form]修复组件内部使用了Object.values低版本浏览器不支持问题 

src/components/input/index.less
-   [ ] 新特性提交
-   [ ] 组件样式改进
-   [ ] 重构
-   [ ] 代码风格优化
=> [Input] 删除input宽度、高度important样式

src/components/tooltip/demos/basic.markdown, src/components/tooltip/index.less
-   [ ] 新特性提交
-   [ ] 组件样式改进
-   [ ] 重构
-   [ ] 代码风格优化
=> :bug: [Tooltip] content 是纯数字或纯英文，显示异常

src/components/tree/index.js, src/components/tree/store.js
-   [ ] 新特性提交
-   [ ] 组件样式改进
-   [ ] 重构
-   [ ] 代码风格优化
=> :art: [Tree] 提示文案调整

src/components/tree/context.js, src/components/tree/index.js, src/components/tree/index.less, src/components/tree/menu.js, src/components/tree/node.js, src/components/tree/store.js
-   [ ] 新特性提交
-   [ ] 组件样式改进
-   [X] 重构
-   [ ] 代码风格优化
说明：
1. 样式调整，和蓝湖上最初的设计保持一致
2. bug 修复，有多个树，交互选中，没有取消选中
3. bug 修复，不允许同时编辑多个节点或者同时新增多个节点
4. bug 修复，树的选中样式和回显样式不一致
=> Fix/Tree: 交互和样式重构

src/components/form/form-item.js
-   [ ] 新特性提交
-   [ ] 组件样式改进
-   [ ] 重构
-   [ ] 代码风格优化
=> :bug: [FormItem] 添加判空处理，使用 remove 方法时报错

src/components/tree/index.js, src/components/tree/store.js
-   [ ] 新特性提交
-   [ ] 组件样式改进
-   [ ] 重构
-   [ ] 代码风格优化
=> :bug: [Tree] 所有实例公用一份数据，导致点击时样式错乱

src/components/input-number/index.js
在form中使用的时候，动态添加inputNumber，移除的时候，元素被移除掉，但是校验还是存在的，导致form表单不能够正常被提交。
-   [x] 文档无须补充
=> [InputNumber] 修复在form中使用元素移除未清除校验问题

package.json, src/components/table/index.less, src/components/table/index.md
-   [ ] 新特性提交
-   [X] 站点、文档改进
-   [X] 组件样式改进
-   [ ] 重构
-   [ ] 代码风格优化
- 修复火狐下固定列功能错位问题, 调整火狐的滚动条样式
- 修复textConfig相互污染问题
- 更新表格组件API
- 清除冗余样式
=> 更新表格组件版本，更新表格API

src/components/form/form-item.js
=> [FormItem] 添加判空处理，使用 remove 方法时报错

src/components/select/index.js, src/utils/flat.js, src/utils/index.js
=> [Select] 增加flat方法，替换Array.flat方法

package.json, src/components/table/index.less, src/components/table/index.md
=> [table]更新api文档

src/components/tree/context.js, src/components/tree/index.js, src/components/tree/index.less, src/components/tree/menu.js, src/components/tree/node.js, src/components/tree/store.js
=> [Tree] 树组件问题修复

package.json
=> [公共依赖] gridmanager-react@0.4.12

scripts/webpack.production.js
-   [x] 新特性提交
多么快使用，提供cdn的方式，支持script方式直接引用
-   [x] 文档无须补充
-   [x] 代码演示无须提供
=> 打包输出umd命名改造，支持script方式引用

src/components/button/demos/loading.markdown, src/components/button/index.js, src/components/button/index.less, src/components/modal/index.less, src/components/modal/modal.js
-   [x] 新特性提交
https://github.com/ShuyunFF2E/cloud-react/issues/341
按钮在处理异步逻辑的时候，点击完以后需要增加一个loading状态，同时按钮disabled
=> [Button] 添加按钮loading状态

src/components/input/demos/textarea.markdown, src/components/input/index.less, src/components/input/index.md, src/components/input/textarea.js
-   [x] 新特性提交
https://github.com/ShuyunFF2E/cloud-react/issues/339
用户输入的时候给正向反馈计数器
=>  [Input.Textarea] 增加计数器功能

src/components/datepicker/date-picker/grid.js, src/components/datepicker/demos/date-picker.markdown
-   [x] 文档无须补充
-   [x] 代码演示无须提供
=> [Datepicker] 修复年月日最大值为当天不能确定的问题

src/components/datepicker/common/picker.js, src/components/datepicker/demos/date-picker.markdown, src/components/datepicker/demos/time-picker.markdown, src/components/datepicker/index.less, src/components/datepicker/index.md
-   [x] 新特性提交
提供API支持是否需要渲染到body上，而不是当前打开的元素
=>  [Datepicker] 添加isAppendToBody 属性，选择日历弹框是否需要渲染在body上

src/components/modal/demos/methodModal.markdown, src/components/modal/index.js, src/components/modal/index.md, src/components/modal/modal.js
-   [X] 新特性提交
-   [ ] 组件样式改进
-   [ ] 重构
-   [ ] 代码风格优化
https://github.com/ShuyunFF2E/cloud-react/issues/340
1、增加createModal方法，支持传入body参数与attributes参数，通过open方式打开弹出框
1、兼容历史写法，也可使用新的写法；
=> :sparkles:[Modal]新增createModal方法

package.json
=> 升级 gridmanager-react@0.4.13

src/components/form/index.less, src/components/input/demos/textarea.markdown, src/components/input/index.less, src/components/input/textarea.js
-   [ ] 新特性提交
-   [ ] 组件样式改进
-   [ ] 重构
-   [ ] 代码风格优化
=> :lipstick: [Input.Textarea] textArea 样式调整

src/components/tree-select/index.less, src/components/tree-select/tree.js
-   [ ] 新特性提交
-   [ ] 组件样式改进
-   [ ] 重构
-   [ ] 代码风格优化
=> :bug: [TreeSelect] 火狐浏览器下滚动样式显示异常

src/components/tooltip/demos/control.markdown, src/components/tooltip/demos/placement.markdown, src/components/tooltip/index.js, src/components/tooltip/index.md, src/components/tooltip/toolView.js
=> [toolTip]修改tooltip定位问题，container增加类名选择

src/components/datepicker/date-range/index.js, src/components/datepicker/demos/date-picker.markdown, src/components/datepicker/index.md
1. 模板引擎中组件都是动态渲染且会触发组件的多次渲染，因为组件的值也是动态获取的，多次动态渲染时rangepicker的值设置不上问题
1. `Rangepicker`组件受控场景下更新时多次比较prevProps和props值出现bug
2. 使用官方标准生命周期API`getDerivedStateFromProps`优化需要计算的问题
`Datepicker.Rangepicker` 组件使用 class component `getDerivedStateFromProps` API 优化计算问题
=> [Datepicker.Rangepicker] 修复在多次动态渲染的复杂场景下计算prevProps和props时不够准确问题

src/components/input-number/index.js
=> :bug: [InputNumber] value设置为0时渲染错误

src/components/form/demos/basic-forms.markdown, src/components/input/index.less
-   [ ] 新特性提交
-   [ ] 组件样式改进
-   [ ] 重构
-   [ ] 代码风格优化
=> :bug: [Input.Textarea] 在form中使用hasCounter属性，样式异常

src/components/upload/demos/custom-request.markdown, src/components/upload/demos/file-list-picture.markdown, src/components/upload/demos/file-list-text.markdown, src/components/upload/demos/picture.markdown, src/components/upload/index.js, src/components/upload/index.md
-   [x] 新特性提交
-   [ ] 组件样式改进
-   [ ] 重构
-   [ ] 代码风格优化
=> [upload]解决自定义样式不生效问题；增加disabled样式；完善文档

package.json, src/components/icon/demos/basic.markdown, src/components/menu/index.js, src/components/select/index.js, src/components/select/utils.js, src/components/tree-select/index.js, src/components/tree-select/single-tree.js, src/components/tree/index.js, src/components/tree/store.js
-   [x] 重构
工具类以后集中维护到 shuyun-utils 里面
=> 使用 shuyunUtils 替换 jeasy

src/components/tree-select/index.less, src/components/tree/index.less, src/components/tree/node.js
-   [ ] 新功能提交
-   [ ] 组件样式改进
-   [ ] 代码风格优化
-   [ ] 重构
1. 火狐浏览器显示有问题；
2. 点击展开收起按钮阻止事件冒泡。帮我发个测试版本
=> :lipstick: 调整 Tree 和 TreeSelect 样式，兼容火狐浏览器

docs/contributor.md, src/components/table/demos/static.markdown
=> 📝update docs

src/components/datepicker/common/picker.js, src/components/datepicker/demos/date-picker.markdown
=>  [Datepicker] 设置defaultValue显示异常

src/components/datepicker/common/picker.js, src/components/datepicker/common/utils.js, src/components/datepicker/date-picker/index.js, src/components/datepicker/demos/date-picker.markdown, src/components/datepicker/demos/month-day-picker.markdown, src/components/datepicker/demos/year-month-picker.markdown, src/components/datepicker/demos/year-picker.markdown, src/components/datepicker/index.less, src/components/datepicker/index.md, src/components/datepicker/month-day/index.js, src/components/datepicker/year-month/index.js, src/components/datepicker/year/index.js
-   [x] 新功能提交
可以自定义日历弹框出现的位置，向上向下，设置为auto自动计算空间位置
=> :sparkles: [Datepicker] 添加position自动定位

src/components/field/demos/basic-forms.markdown, src/components/field/index.js
-   [ ] 新功能提交
-   [ ] 组件样式改进
-   [ ] 代码风格优化
-   [ ] 重构
=> [field] getErrors方法修复

src/components/input/demos/onChange.markdown, src/components/input/index.js
-   [ ] 新功能提交
-   [ ] 组件样式改进
-   [ ] 代码风格优化
-   [ ] 重构
=> :bug: 解决 input 在中文输入法下的 bug

src/components/tooltip/demos/basic.markdown, src/components/tooltip/demos/control.markdown, src/components/tooltip/index.js, src/components/tooltip/toolView.js
-   [X] 新功能提交
-   [ ] 组件样式改进
-   [ ] 代码风格优化
-   [ ] 重构
=> :sparkles:[tooltip]支持content传入jsx

jest.config.js, package.json, src/components/button/__test__/__snapshots__/index.test.js.snap, src/components/button/__test__/index.test.js, src/components/button/index.md, tests/shared/mountTest.js
=> 【button】单元测试完成

src/components/input/demos/onChange.markdown, src/components/input/index.js, src/components/input/index.less
-   [ ] 新功能提交
-   [ ] 组件样式改进
-   [ ] 代码风格优化
-   [ ] 重构
=> :bug: [Input] 修正 shouldComponent 逻辑；size等于small，hover时输入框变高

src/components/toggle/__tests__/__snapshots__/index.test.js.snap, src/components/toggle/__tests__/index.test.js, src/components/toggle/index.js, src/components/toggle/index.md
=> [Toggle]单元测试完成

src/components/checkbox/__test__/__snapshots__/group.test.js.snap, src/components/checkbox/__test__/__snapshots__/index.test.js.snap, src/components/checkbox/__test__/group.test.js, src/components/checkbox/__test__/index.test.js, src/components/checkbox/demos/basic.markdown, src/components/checkbox/index.js
=> ✅ [Checkbox] 添加单元测试

src/components/checkbox/__test__/group.test.js, src/components/checkbox/__test__/index.test.js
=> 🚨 [checkbox] fix  eslint error

jest.config.js, jsconfig.json, src/components/button/__test__/index.test.js, src/components/checkbox/__test__/index.test.js, src/components/toggle/__tests__/index.test.js, webpack.config.js
=> 🔧 alias jest config to resolve tests folder

src/components/input/textarea.js
-   [ ] 新功能提交
-   [ ] 组件样式改进
-   [ ] 代码风格优化
-   [ ] 重构
=> :bug: [TextArea] counter 添加判空处理

src/components/tips/__test__/__snapshots__/index.test.js.snap, src/components/tips/__test__/index.test.js
-   [ ] 新功能提交
-   [ ] 组件样式改进
-   [ ] 代码风格优化
-   [ ] 重构
=> ✅ [Tips] 添加单元测试

src/components/input/__test__/__snapshots__/input.test.js.snap, src/components/input/__test__/__snapshots__/textarea.test.js.snap, src/components/input/__test__/input.test.js, src/components/input/__test__/textarea.test.js, src/components/input/demos/textarea.markdown, src/components/input/index.js, src/components/input/textarea.js
-   [ ] 新功能提交
-   [ ] 组件样式改进
-   [ ] 代码风格优化
-   [ ] 重构
=> ✅ [Input] 添加单元测试

src/components/loading/demos/basic.markdown, src/components/loading/demos/embed.markdown, src/components/loading/index.js, src/components/loading/index.md
-   [ ] 新功能提交
-   [ ] 组件样式改进
-   [ ] 代码风格优化
-   [ ] 重构
=> [loading]增加外部控制样式

scripts/generate-index.js, src/components/pagination/demos/basic.markdown, src/components/pagination/demos/change.markdown, src/components/pagination/demos/jump.markdown, src/components/pagination/demos/more.markdown
-   [x] 打包时候移除pagination组件
在业务中没有任何使用，保留源代码，只在打包时候做移除，后期需要再进行优化使用
=> 🔥 [pagination] 移除

src/components/pagination/__test__/__snapshots__/index.test.js.snap, src/components/pagination/__test__/index.test.js, src/components/pagination/index.js
-   [ ] 新功能提交
-   [ ] 组件样式改进
-   [ ] 代码风格优化
-   [ ] 重构
=> ✅ [Pagination] 添加单元测试

src/components/loading/__test__/__snapshots__/index.test.js.snap, src/components/loading/__test__/index.test.js, src/components/loading/index.js
=> ✅ [loading] 单元测试完成

src/components/pagination/index.js, src/components/table-pagination/__test__/__snapshots__/index.test.js.snap, src/components/table-pagination/__test__/index.test.js, src/components/table-pagination/index.js
-   [ ] 新功能提交
-   [ ] 组件样式改进
-   [ ] 代码风格优化
-   [ ] 重构
=> ✅ [TablePagination] 添加单元测试

package.json
=> 🥅 eslint waring auto fix

src/components/step/__test__/__snapshots__/index.test.js.snap, src/components/step/__test__/__snapshots__/item.test.js.snap, src/components/step/__test__/index.test.js, src/components/step/__test__/item.test.js
=> ✅ [Step] 添加单元测试

src/components/message/__test__/index.test.js, src/components/message/index.js
=> ✅ [Message] 单元测试编写

package.json, src/components/tooltip/demos/basic.markdown, src/components/tooltip/demos/control.markdown, src/components/tooltip/demos/placement.markdown, src/components/tooltip/demos/theme.markdown, src/components/tooltip/index.js, src/components/tooltip/index.less, src/components/tooltip/index.md, src/components/tooltip/toolView.js
-   [x] 新功能提交
-   [ ] 组件样式改进
-   [x] 代码风格优化
-   [x] 重构
1. content字段需要同时支持支持JSX格式的内容
2. Tooltip组件需要适配ifrmae且在弹框下场景
1. 优化Tooltip实现方式
2. 废除`container`和`clear`属性
3. `content`属性的内容支持传JSX格式和普通html字符串格式
=> [Tolltip] 优化组件实现方式，内容格式支持jsx组件和html内容

package.json
更新依赖包版本号: gridmanager-react@0.5.1 > gridmanager-react@0.5.2
-   [ ] 新功能提交
-   [ ] 组件样式改进
-   [ ] 代码风格优化
-   [ ] 重构
解决了表格中存在fixed="left"且不存在fixed="right"时，表格渲染报错问题
=> update table version

src/components/select/__test__/__snapshots__/index.test.js.snap, src/components/select/__test__/__snapshots__/multi.test.js.snap, src/components/select/__test__/index.test.js, src/components/select/__test__/multi.test.js, src/components/select/index.js, src/components/select/views/multi-select.js, src/components/select/views/selected.js
=> ✅ [Select] 添加单元测试

.prettierignore, src/components/input-number/index.md, src/components/input-number/util.js
=> 🐛 [InputNumber] value初始值为空问题修复

src/components/upload/constant.js, src/components/upload/demos/basic.markdown, src/components/upload/http.js, src/components/upload/index.js, src/components/upload/index.md
-   [X] 新功能提交
-   [ ] 组件样式改进
-   [ ] 代码风格优化
-   [ ] 重构
1、在文件上传前需要弹出提示框询问是否确认上传，并给出提示信息，因此增加了showBeforeConfirm属性，控制是否在上传文件前需要提示框；
2、增加isShowIcon属性，用于控制上传按钮前是否显示上传图标，因为在某些情景中，只需要使用按钮，不需要图标；
3、修复了在上传时formData中name的值不是`file`导致上传后后端未识别是文件的问题；
=> [Upload]Bug修复，增加新属性

package.json, src/components/tooltip/__test__/index.test.js, src/components/tooltip/demos/control.markdown, src/components/tooltip/index.js, src/components/tooltip/index.md, tests/utils.js
=> ✅ [Tooltip] 增加单元测试

src/components/message/index.less
-   [ ] 新功能提交
-   [x] 组件样式改进
-   [ ] 代码风格优化
-   [ ] 重构
=> :art: [Message] 修改Message组件淡入效果时间

src/components/menu/__test__/__snapshots__/index.test.js.snap, src/components/menu/__test__/index.test.js, src/components/menu/context.js, src/components/menu/demos/basic.markdown, src/components/menu/demos/controlled.markdown, src/components/menu/demos/header.markdown, src/components/menu/demos/link.markdown, src/components/menu/demos/source.markdown, src/components/menu/index.js, src/components/menu/index.md, src/components/menu/menu-item.js, src/components/menu/sub-menu.js
-   [x] 新功能提交
-   [ ] 组件样式改进
-   [ ] 代码风格优化
-   [ ] 重构
=>  [Menu]增加Menu单元测试

src/components/tooltip/__test__/index.test.js, src/components/tooltip/index.js
-   [ ] 新功能提交
-   [ ] 组件样式改进
-   [ ] 代码风格优化
-   [ ] 重构
-   [x] 其他改动（是关于什么的改动？）
=> ✅ [Tooltip] 添加单元测试

src/components/select/__test__/index.test.js, src/components/select/demos/basic.markdown, src/components/select/index.js, src/components/select/index.md
-   [ ] 新功能提交
-   [ ] 文档已补充
-   [ ] 代码演示已提供
=> ✨ [Select] 单选添加点击选项返回原始数据

src/components/tree-select/__test__/__snapshots__/index.test.js.snap, src/components/tree-select/__test__/__snapshots__/tree.test.js.snap, src/components/tree-select/__test__/index.test.js, src/components/tree-select/__test__/tree.test.js, src/components/tree-select/const.js, src/components/tree-select/demos/basic.markdown, src/components/tree-select/demos/multiple.markdown, src/components/tree-select/index.js, src/components/tree-select/index.less, src/components/tree-select/index.md, src/components/tree-select/selected.js, src/components/tree-select/single-tree.js, src/components/tree-select/tree.js
-   [x] 新功能提交
-   [ ] 文档已补充
-   [ ] 代码演示已提供
=> ✨ [TreeSelect] 添加单元测试/添加isAppendToBody参数/删除getPopupContainer

.eslintrc, package.json, src/components/modal/_test_/__snapshots__/index.test.js.snap, src/components/modal/_test_/cerateModal.test.js, src/components/modal/_test_/confirm.test.js, src/components/modal/_test_/index.test.js, src/components/modal/index.js, src/components/modal/modal.js, src/components/modal/prompt.js
-   [x] 新功能提交
-   [ ] 组件样式改进
-   [ ] 代码风格优化
-   [ ] 重构
=> ✅ [Modal] 添加单元测试

src/components/modal/modal.js
-   [ ] 新功能提交
-   [ ] 组件样式改进
-   [ ] 代码风格优化
-   [ ] 重构
=> :bug: [Modal]修复关闭弹框时控制台报错问题

src/components/select/index.js
=> 🐛 [Select] 修复value更新时会刷新open状态的问题

src/components/field/index.js, src/components/form/__test__/__snapshots__/form.test.js.snap, src/components/form/__test__/form.test.js
=> ✅[Form, Field] add unit test

package.json, src/components/table-lite/index.js, src/components/table-lite/index.less, src/components/table-lite/index.md, src/components/table/demos/top-full.markdown, src/components/table/index.less
-   [X] 新功能提交
-   [X] 站点、文档改进
-   [X] 组件样式改进
-   [ ] 代码风格优化
-   [ ] 重构
- table组件增加嵌套表头功能、tr|td事件触发tooltip功能、折叠行功能，树型结构小图标样式调整
- table-lite组件修复树型结构数据为空样式问题，树型结构小图标样式调整, doc更新
=> Table fold

src/components/select/__test__/index.test.js
=> 🚑 [Select] 修复单元测试

package.json
=> 📌eslint-plugin-react依赖包锁死7.20.0

src/components/checkbox/__test__/index.test.js, src/components/form/__test__/form.test.js, src/components/form/render-children.js, src/components/menu/context.js, src/components/modal/modal.js, src/components/select/__test__/index.test.js, src/components/select/index.js, src/components/select/views/multi-select.js, src/components/select/views/option.js, src/components/select/views/selected.js, src/components/select/views/single-select.js, src/components/step/index.js, src/components/step/item.js, src/components/tabs/index.js, src/components/tree/index.js, src/components/tree/node.js, src/components/upload/list.js
-   [x] 重构
空函数统一调用工具类中的方法，不用每次需要使用的时候单独声明。
=> ♻️统一空函数引用noop

src/components/input/index.js, src/components/input/index.less
=> 🐛 [Input] 修复在hasClear时placeholder过长的样式问题

src/components/input-number/__test__/index.test.js, src/components/input-number/index.js, src/components/input-number/index.md
=> ✨ [InputNumber] 增加onEnter事件

src/components/input/demos/onChange.markdown, src/components/input/index.js, src/components/input/index.md
-   [ ] 新功能提交
-   [ ] 组件样式改进
-   [ ] 代码风格优化
-   [ ] 重构
=> :bug: [Input] 提供配置参数 useComposition，解决中文输入法下的 bug

src/components/form/index.less
-   [ ] 新功能提交
-   [x] 组件样式改进
-   [ ] 代码风格优化
-   [ ] 重构
1. Form表单中表单项校验状态的样式影响了部分组件内部的样式
2. 通过更精准的CSS选择器匹配规则查找元素
修复`Form`表单中表单项校验状态的样式影响了部分组件内部的样式问题
=> [Form]修复表单项校验状态的样式会影响部分组件内部样式bug

src/components/select/__test__/multi.test.js, src/components/select/demos/multiple.markdown, src/components/select/index.js, src/components/select/index.md, src/components/select/views/selected.js
=> ✨[Select] 添加全选是否显示“全选“配置

src/components/tooltip/index.less
-   [ ] 新功能提交
-   [X ] 组件样式改进
-   [ ] 代码风格优化
-   [ ] 重构
=> :lipstick:[tooltip]恢复tooltip默认宽度

src/components/modal/index.js
-   [x] 新功能提交
-   [ ] 组件样式改进
-   [ ] 代码风格优化
-   [ ] 重构
1. 弹框组件在iframe场景下能够获取顶层document，业务方也需要共享当前document
2. 将弹框获取到的顶层document通过静态属性的方式导出，供其他组件/模块使用
`Modal`组件新增`ConfigProvider`静态属性
=> [Modal]弹框组件新增静态属性 ConfigProvider

src/components/style/core/normalize.less
-   [ ] 新功能提交
-   [X] 组件样式改进
-   [ ] 代码风格优化
-   [ ] 重构
1、全局增加自定义滚动条样式，避免在windows和mac环境下滚动条样式不一问题；
=> 增加全局自定义滚动条样式

package.json
=> 📌 固定 dependencies libs 版本

src/components/datepicker/common/picker.js
=> 🐛 [Datepicker] 修复日期选择器点击日历图标打开选择器无法关闭的问题

src/components/select/demos/basic.markdown, src/components/select/index.js, src/components/select/index.less, src/components/select/index.md, src/components/select/views/option.js, src/components/select/views/selected.js
-   [ ] 新功能提交
-   [ ] 组件样式改进
-   [ ] 代码风格优化
-   [ ] 重构
=> :art: [Select] 样式优化

src/components/upload/index.js
-   [ ] 新功能提交
-   [ x] 日常 bug 修复
-   [ ] 组件样式改进
-   [ ] 代码风格优化
-   [ ] 重构
=> :bug:[upload]修改上传异常时，未对原数据处理，导致不能触发change事件

src/components/checkbox/demos/layout.markdown, src/components/checkbox/index.less
-   [ ] 新功能提交
-   [ ] 组件样式改进
-   [ ] 代码风格优化
-   [ ] 重构
=> :bug: [CheckboxGroup] 横向布局超长换行

src/components/form/__test__/form.test.js, src/components/menu/__test__/index.test.js
=> 🚨fix eslint warning

src/components/datepicker/common/time.js
-   [ ] 新功能提交
-   [ ] 组件样式改进
-   [ ] 代码风格优化
-   [ ] 重构
=> 🐛 [DateRange] 修复修改时间时会触发onChange事件

src/components/tree/demos/basicSelector.markdown, src/components/tree/demos/changeSelectedValue.markdown, src/components/tree/demos/defineStyle.markdown, src/components/tree/index.js, src/components/tree/index.less, src/components/tree/index.md, src/components/tree/menu.js, src/components/tree/node.js
-   [X] 新功能提交
-   [ ] 组件样式改进
-   [ ] 代码风格优化
-   [ ] 重构
1、增加breakCheckbox属性，支持复选框与文字分离；
2、增加showErrMsg属性，支持自定义错误信息；
3、调整只存在根节点时仍然可删除逻辑；
4、不支持删除的节点删除按钮不可点击；
=> [tree]调整样式,修复bug,增加新属性

package.json, src/components/message/index.js, src/components/upload/index.js, src/components/upload/index.md
-   [X] 新功能提交
-   [X] 站点、文档改进
-   [ ] 组件样式改进
-   [ ] 代码风格优化
-   [ ] 重构
- Upload增加onClick事件
- 完善Upload文档
- Table依赖包gridmanager-react更新至1.7.18
- Message清除console
=> upload增加参数、table依赖项更新、message移除console

src/components/tree/demos/basicSelector.markdown, src/components/tree/demos/changeSelectedValue.markdown, src/components/tree/demos/defineStyle.markdown, src/components/tree/index.js, src/components/tree/index.less, src/components/tree/index.md, src/components/tree/menu.js, src/components/tree/node.js
-   [ ] 新功能提交
-   [ ] 组件样式改进
-   [ ] 代码风格优化
-   [ ] 重构
修复数据回显错误问题
=> :bug: [Tree] fix bug

src/components/plaintext/demos/basic.markdown, src/components/plaintext/index.js, src/components/plaintext/index.less, src/components/plaintext/index.md
-   [x] 查看明密文切换组件
脱敏数据需要支持切换明密文切换
增加查看明密文组件
-   [x] 文档已补充
-   [x] 代码演示已提供
=> ✨[plaintext] 查看明密文切换组件

src/components/input-tag/demos/basic.markdown, src/components/input-tag/demos/disabled.markdown, src/components/input-tag/demos/separator.markdown, src/components/input-tag/demos/style.markdown, src/components/input-tag/index.js, src/components/input-tag/index.less, src/components/input-tag/index.md
-   [x] 多文本输入组件
需要能够快速在一个文本框输入多个文本，分隔为多段
-   [x] 文档已补充
-   [x] 代码演示已提供
=> ✨ [Input-tag]  多文本输入组件

src/components/modal/_test_/confirm.test.js, src/components/modal/demos/confirm.markdown, src/components/modal/index.md, src/components/modal/modal.js, src/components/modal/prompt.js
-   [x] 新功能提交
-   [ ] 组件样式改进
-   [ ] 代码风格优化
-   [ ] 重构
1. `Modal.methods()`类型组件需要支持可更改按钮文案
2. `Modal.confirm({ okText: 'done', cancelText: 'close' })`
`Modal.methods({...})`类型组件新增`okText`、`cancelText` API
=> :sparkles:[Modal] Modal.methods类型组件新增`okText`,`cancelText`字段

package.json
-   [ ] 新功能提交
-   [X] 组件样式改进
-   [ ] 代码风格优化
-   [ ] 重构
Table新增汇总行置底浮动功能
=> [Table]:新增汇总行置底浮动功能

src/components/tree/demos/basicSelector.markdown, src/components/tree/index.js, src/components/tree/index.less, src/components/tree/index.md, src/components/tree/node.js
-   [X] 新功能提交
-   [ ] 组件样式改进
-   [ ] 代码风格优化
-   [ ] 重构
=> :sparkles: [tree] 增加breakCheeckbox属性支持复选框与文字分离

src/components/datepicker/utils.js
-   [ ] 新功能提交
-   [ ] 组件样式改进
-   [ ] 代码风格优化
-   [ ] 重构
=> :bug: [Datepicker] 输入“1/31”，时间弹窗没有自动同步时间

src/components/upload/demos/basic.markdown, src/components/upload/http.js, src/components/upload/index.js, src/components/upload/index.md
-   [X] 新功能提交
-   [ ] 组件样式改进
-   [ ] 代码风格优化
-   [ ] 重构
=> ✨ [Upload] 支持在 FormData 中传入额外参数

src/components/input/index.js
-   [ ] 新功能提交
-   [ ] 组件样式改进
-   [ ] 代码风格优化
-   [ ] 重构
=> :bug: [Input] 表单中只有一个input时，回车导致页面刷新

src/components/bread-crumbs/__tests__/__snapshots__/index.test.js.snap, src/components/bread-crumbs/__tests__/index.test.js, src/components/bread-crumbs/demos/basic.markdown, src/components/bread-crumbs/index.js, src/components/bread-crumbs/index.less, src/components/bread-crumbs/index.md, src/components/form/__test__/__snapshots__/form.test.js.snap
-   [X] 新功能提交
-   [ ] 组件样式改进
-   [ ] 代码风格优化
-   [ ] 重构
新增面包屑组件
=> [Breadcrumbs]:新增面包屑组件

src/components/table-lite/demos/basic.markdown, src/components/table-lite/index.js
-   [ ] 新功能提交
-   [ ] 组件样式改进
-   [ ] 代码风格优化
-   [ ] 重构
columnData变更后不触发runder问题修复
=> [TableLite]: columnData变更后不触发runder问题修复

.babelrc, package.json
-   [ ] 新功能提交
-   [ ] 组件样式改进
-   [ ] 代码风格优化
-   [ ] 重构
-   [X] 其他改动（babelrc配置文件）
浏览器版本支持调整为chrome:56,firefox:59, 取消eslint自动修改
=> confing: 浏览器版本支持调整为chrome:56,firefox:59

src/components/input-number/util.js
-   [ ] 新功能提交
-   [x ] 日常 bug 修复
-   [ ] 组件样式改进
-   [ ] 代码风格优化
-   [ ] 重构
-   [x ] 文档已补充或无须补充
=> [InputNumber]修改精度取值方法（整数不补零）

src/components/tooltip/index.js, src/components/tooltip/index.less, src/components/tooltip/index.md, src/components/tooltip/toolView.js
-   [x] 新功能提交
-   [ ] 组件样式改进
-   [ ] 代码风格优化
-   [ ] 重构
=> :sparkles:[Tooltip]增加卡片自定义样式及增加鼠标可移入自

src/components/tooltip/toolView.js
-   [ ] 新功能提交
-   [ ] 组件样式改进
-   [ ] 代码风格优化
-   [ ] 重构
-   [x] 其他改动（是关于什么的改动？）
=> [Tooltip]:处理滚动元素水平位置的偏移

src/components/input-number/index.js
-   [ ] 新功能提交
-   [ ] 组件样式改进
-   [ ] 代码风格优化
-   [ ] 重构
=> :bug: [InputNumber]blur执行顺序修改

src/components/message/__test__/index.test.js, src/components/message/index.js, src/components/message/index.md
-   [X] 新功能提交
-   [ ] 组件样式改进
-   [ ] 代码风格优化
-   [ ] 重构
解决Message不能重置样式问题
新增参数className
=> [Message]新增option.className参数

src/components/input-number/demos/basic.markdown, src/components/input-number/util.js
-   [ ] 新功能提交
-   [ ] 组件样式改进
-   [ ] 代码风格优化
-   [ ] 重构
=> [InputNumber]修改效验问题

docs/contributor.md, scripts/generate-version.js, src/components/datepicker/common/picker.js, src/components/datepicker/common/utils.js, src/components/datepicker/constant.js
-   [ ] 新功能提交
-   [ ] 组件样式改进
-   [ ] 代码风格优化
-   [ ] 重构
=> 🐛[DatePicker]弹框右边界碰撞检测

src/components/modal/modal.js
Reverts ShuyunFF2E/cloud-react#568
=> Revert "修复iframe下使用弹窗，会在父窗口head遗留style 影响其余样式"

src/components/modal/modal.js
-   [ ] 新功能提交
-   [ ] 组件样式改进
-   [ ] 代码风格优化
-   [ ] 重构
=> 为iframe下modal添加额外的class区分样式

.umirc.ts
-   [ ] 新功能提交
-   [ ] 组件样式改进
-   [ ] 代码风格优化
-   [ ] 重构
=> banner图换地址

.umirc.ts
-   [ ] 新功能提交
-   [ ] 组件样式改进
-   [ ] 代码风格优化
-   [ ] 重构
=> Fix banner

.umirc.ts
-   [ ] 新功能提交
-   [ ] 组件样式改进
-   [ ] 代码风格优化
-   [ ] 重构
=> 增加静态资源文件Js/css/font hash防止缓存

.github/workflows/Sync2Gitee.yml
-   [ ] 新功能提交
-   [ ] 组件样式改进
-   [ ] 代码风格优化
-   [ ] 重构
-   [x] 自动同步仓库到gitee,用于企业流水线clone
=> Sync gitee

.umirc.ts
-   [ ] 新功能提交
-   [ ] 组件样式改进
-   [ ] 代码风格优化
-   [ ] 重构
=> 组件库站点menu版本号

.umirc.ts, docs/color.less, docs/default.md, docs/setColor.md, docs/theme.md, package.json, scripts/generate-index.js, src/components/c-cascader/demos/disable.md, src/components/c-cascader/index.js, src/components/c-cascader/index.less, src/components/c-cascader/mixin.less, src/components/c-picker/demos/range-picker.md, src/components/c-picker/pickers/date-range.js, src/components/c-picker/style/panel.less, src/components/c-picker/style/range.less, src/components/c-table/index.js, src/components/c-table/index.less, src/components/c-table/index.md, src/components/c-table/util.js, src/components/index.js
-   [x] 新功能提交
-   [ ] bugfix
-   [ ] 组件样式改进
-   [ ] 代码风格优化
-   [ ] 重构
=> V1 develop

.umirc.ts, docs/default.md, docs/demo.md, docs/entry.md, docs/index.md, docs/setColor.md, docs/theme.md, src/components/radio/demos/basic-radio.md, src/components/radio/demos/complex.md, src/components/radio/demos/disabled.md, src/components/radio/demos/group.md, src/components/radio/demos/layout.md, src/components/radio/group.js, src/components/radio/index.js
-   [ ] 新功能提交
-   [x] bugfix
-   [ ] 组件样式改进
-   [ ] 代码风格优化
-   [ ] 重构
=> 【Radio】fix: 修复radioGroup组件disabled，导致单独radio无法设置disabed问题

src/components/c-table/demos/disabled0.md, src/components/c-table/demos/disabled1.md, src/components/c-table/demos/fixed-column.md, src/components/c-table/demos/page.md, src/components/c-table/demos/radio.md, src/components/c-table/demos/refresh-table.md, src/components/c-table/index.js, src/components/pagination/index.less
-   [x] 新功能提交
-   [x] bugfix
-   [ ] 组件样式改进
-   [ ] 代码风格优化
-   [ ] 重构
=> Feat/cRable 选中行回调添加参数；单选表格报错修改

src/components/upload/demos/file-list-picture.md, src/components/upload/index.js, src/components/upload/index.less, src/components/upload/list.js
-   [x] 组件样式改进
1.上传的图标（加号）需要更改为16px
2.上传图片后，因添加了属性margin: 0 12px 8px 0; 会向上移动
3.上传图片后，一些小图不需要填充满整个方框，会变形，需要按正常比例尺寸居中展示就好
优化上传组件样式
-   [ ] 文档无须补充
-   [ ] 代码演示无须提供
=> Feat upload

.eslintrc, src/components/c-table/index.js, src/components/c-table/index.less, src/components/input-tag/index.less, src/components/input/demos/counter.md, src/components/input/demos/mix.md, src/components/input/index.js, src/components/input/index.less, src/components/input/index.md, src/components/input/textarea.js, src/components/message/demos/basic-close-message.md, src/components/message/demos/basic-deepen-message.md, src/components/message/demos/basic-message.md, src/components/message/demos/basic-noicon-message.md, src/components/message/index.js, src/components/message/index.less, src/components/message/index.md, src/components/popover/demos/basic.md, src/components/popover/index.js, src/components/style/core/color.less, src/components/table-pagination/index.less, src/components/table/index.js, src/components/upload/demos/file-list-picture.md, src/components/upload/index.js, src/components/upload/index.less, src/components/upload/list.js
-   [ ] 新功能提交
-   [ ] bugfix
-   [x] 组件样式改进
-   [ ] 代码风格优化
-   [ ] 重构
=> [Message]组件UI改版

src/components/input/index.js
-   [ ] 新功能提交
-   [x] bugfix
-   [ ] 组件样式改进
-   [ ] 代码风格优化
-   [ ] 重构
=> [Input]fix:oncomposition时输入异常

src/components/modal/demos/async.md, src/components/modal/demos/basic-modal.md, src/components/modal/demos/callback.md, src/components/modal/demos/component.md, src/components/modal/demos/confirm.md, src/components/modal/demos/conplex.md, src/components/modal/demos/defineInfoStyle.md, src/components/modal/demos/defineTpl.md, src/components/modal/demos/hasFooter.md, src/components/modal/demos/iframe-current.md, src/components/modal/demos/info.md, src/components/modal/demos/methodModal.md, src/components/modal/demos/nest.md, src/components/modal/demos/style.md, src/components/modal/index.js, src/components/modal/index.less, src/components/modal/index.md, src/components/modal/modal.js, src/components/modal/prompt.js
-   [x] 新功能提交
-   [ ] bugfix
-   [ ] 组件样式改进
-   [ ] 代码风格优化
-   [ ] 重构
=> [Message]新增区分在顶级窗口或者当前子窗口参数showType

.eslintrc, src/components/c-menu/index.less, src/components/message/demos/basic-close-message.md, src/components/message/demos/basic-deepen-message.md, src/components/message/demos/basic-message.md, src/components/message/demos/basic-noicon-message.md, src/components/message/index.js, src/components/message/index.less, src/components/message/index.md, src/components/style/core/color.less, src/components/tabs/index.js, src/components/upload/constant.js, src/components/upload/demos/basic-upload.md, src/components/upload/demos/file-list-text.md, src/components/upload/index.js, src/components/upload/index.less, src/components/upload/list.js
-   [X] 新功能提交
-   [X] bugfix
-   [ ] 组件样式改进
-   [ ] 代码风格优化
-   [ ] 重构
=> [Message]UI 升级；[Upload]新增图标；[Menu]修复下拉菜单不展示的问题；

.eslintrc, src/components/form/demos/basic-forms.md, src/components/form/form-item.js, src/components/form/index.js, src/components/form/index.less, src/components/form/index.md, src/components/input-number/index.js, src/components/input-number/index.less, src/components/input-tag/index.js, src/components/input/demos/disabled.md, src/components/input/demos/mix.md, src/components/input/demos/size.md, src/components/input/index.js, src/components/input/index.less, src/components/style/index.less
-   [ ] 新功能提交
-   [ ] bugfix
-   [x] 组件样式改进
-   [ ] 代码风格优化
-   [ ] 重构
=> [Input Form]UI升级

src/components/complex-radio/demos/basic.md, src/components/complex-radio/index.js, src/components/complex-radio/index.less, src/components/complex-radio/index.md
-   [ ] 新功能提交
-   [x] bugfix
-   [x] 组件样式改进
-   [x] 代码风格优化
-   [ ] 重构
=> 【complexRadio】fix: 修正关于markdown的格式以及规范文本demo书写，增加关于功能的缺失

src/components/radio/demos/basic-radio.md, src/components/radio/demos/complex.md, src/components/radio/demos/disabled.md, src/components/radio/demos/group.md, src/components/radio/demos/layout.md, src/components/radio/index.js, src/components/radio/index.less
-   [ ] 新功能提交
-   [x] bugfix
-   [x] 组件样式改进
-   [x] 代码风格优化
-   [ ] 重构
=> 【Radio】fix: 修正关于markdown的格式以及规范文本demo书写，增加关于功能的缺失

src/components/checkbox/index.less, src/components/complex-checkbox/demos/basic.md, src/components/complex-checkbox/index.js, src/components/complex-checkbox/index.less, src/components/complex-radio/demos/basic.md
-   [ ] 新功能提交
-   [x] bugfix
-   [x] 组件样式改进
-   [ ] 代码风格优化
-   [ ] 重构
=> checkbox complex-checkbox修改

src/components/tree/index.js
-   [ ] 新功能提交
-   [ ] bugfix
-   [x] 组件样式改进
-   [ ] 代码风格优化
-   [ ] 重构
=> [Tree]修复树搜索下出现滚动条

scripts/generate-version.js
-   [ ] 新功能提交
-   [ ] bugfix
-   [ ] 组件样式改进
-   [ ] 代码风格优化
-   [ ] 重构
-   [x] 其他改动（是关于什么的改动？）
=> infra:修改发布版本号脚本

docs/color.less, src/components/select/demos/basic.md, src/components/select/demos/disabled.md, src/components/select/demos/sizeSelect.md
-   [ ] 新功能提交
-   [ ] bugfix
-   [x] 组件样式改进
-   [ ] 代码风格优化
-   [ ] 重构
=> 【cloud-select】修改关于select影响全局的样式

src/components/button/demos/basic-button.md, src/components/button/demos/block.md, src/components/button/demos/color-button.md, src/components/button/demos/disabled.md, src/components/button/demos/group.md, src/components/button/demos/icon-button.md, src/components/button/demos/loading.md, src/components/button/demos/size.md, src/components/button/index.js, src/components/button/index.less, src/components/button/index.md, src/components/c-picker/demos/more-picker.md, src/components/c-picker/demos/range-picker.md, src/components/c-picker/index.md, src/components/c-picker/pickers/date-range.js, src/components/c-picker/pickers/date.js, src/components/c-picker/pickers/time.js, src/components/c-picker/style/input.less, src/components/c-picker/style/panel.less, src/components/c-picker/style/range.less
-   [x] 新功能提交
-   [ ] bugfix
-   [x] 组件样式改进
-   [ ] 代码风格优化
-   [ ] 重构
1. UI 新增了【面型】按钮
2. UI 对 CPicker 样式提出了一些修改点
=> 【Button】增加面型按钮【CPicker】校对 UI

package.json, scripts/generate-version.js, src/components/index.js, src/components/input/demos/basic-input.md, src/components/input/index.js
-   [ ] 新功能提交
-   [x] bugfix
-   [ ] 组件样式改进
-   [ ] 代码风格优化
-   [ ] 重构
=> [Input]fix:Input blur时报错

src/components/index.js, src/components/input/demos/basic-input.md, src/components/input/index.js
-   [ ] 新功能提交
-   [x] bugfix
-   [ ] 组件样式改进
-   [ ] 代码风格优化
-   [ ] 重构
=> [Input]fix:合成事件报错

package.json, scripts/generate-version.js, src/components/button/demos/basic-button.md, src/components/button/demos/block.md, src/components/button/demos/color-button.md, src/components/button/demos/disabled.md, src/components/button/demos/group.md, src/components/button/demos/icon-button.md, src/components/button/demos/loading.md, src/components/button/demos/size.md, src/components/button/index.js, src/components/button/index.less, src/components/button/index.md, src/components/c-picker/demos/more-picker.md, src/components/c-picker/demos/range-picker.md, src/components/c-picker/index.md, src/components/c-picker/pickers/date-range.js, src/components/c-picker/pickers/date.js, src/components/c-picker/pickers/time.js, src/components/c-picker/style/input.less, src/components/c-picker/style/panel.less, src/components/c-picker/style/range.less, src/components/index.js, src/components/input/demos/basic-input.md, src/components/input/index.js
-   [x] 新功能提交
-   [ ] bugfix
-   [ ] 组件样式改进
-   [ ] 代码风格优化
-   [ ] 重构
=> [Button]feat:icon支持传入dom

src/components/c-picker/style/range.less
-   [ ] 新功能提交
-   [x] bugfix
-   [ ] 组件样式改进
-   [ ] 代码风格优化
-   [ ] 重构
=> 【CPicker】修复大尺寸下时间段选择中间的符号对齐问题

src/components/modal/index.less
-   [ ] 新功能提交
-   [ ] bugfix
-   [x] 组件样式改进
-   [ ] 代码风格优化
-   [ ] 重构
=> [Modal]部分UI样式细化修改

src/components/c-picker/style/range.less, src/components/message/index.less
-   [ ] 新功能提交
-   [ ] bugfix
-   [x] 组件样式改进
-   [ ] 代码风格优化
-   [ ] 重构
=> [Message]最大宽度调整为920

.eslintrc, src/components/bread-crumbs/demos/basic-bread-crumbs.md, src/components/field/demos/basic-forms.md, src/components/form/demos/basic-forms.md, src/components/form/form-item.js, src/components/form/index.js, src/components/form/index.less, src/components/form/index.md, src/components/input-number/index.js, src/components/input-number/index.less, src/components/input-tag/index.js, src/components/input/demos/disabled.md, src/components/input/demos/mix.md, src/components/input/demos/size.md, src/components/input/index.js, src/components/input/index.less, src/components/style/index.less
-   [ ] 新功能提交
-   [ ] bugfix
-   [x] 组件样式改进
-   [ ] 代码风格优化
-   [ ] 重构
=> [Input&Form]UI升级

src/components/radio/index.js
-   [ ] 新功能提交
-   [x] bugfix
-   [ ] 组件样式改进
-   [ ] 代码风格优化
-   [ ] 重构
=> 【radio】提交修复关于radio的未定义方法

src/components/radio/group.js
-   [ ] 新功能提交
-   [x] bugfix
-   [ ] 组件样式改进
-   [ ] 代码风格优化
-   [ ] 重构
=> 【Radio】修复关于报错正式环境无法展示问题

src/components/radio/group.js
-   [ ] 新功能提交
-   [x] bugfix
-   [ ] 组件样式改进
-   [ ] 代码风格优化
-   [ ] 重构
=> 【radio】修复radio的线上问题

src/components/icon/demos/icon-list.md, src/components/icon/index.js, src/components/icon/styles/icon.less, src/utils/index.js, src/utils/module.js
-   [ ] 新功能提交
-   [ ] bugfix
-   [x] 组件样式改进
-   [ ] 代码风格优化
-   [ ] 重构
=> Feat new icons

.fatherrc.ts, src/components/cascade/index.js
-   [ ] 新功能提交
-   [x] bugfix
-   [ ] 组件样式改进
-   [ ] 代码风格优化
-   [ ] 重构
=> 修改cascade问题

src/components/tree/index.js
-   [ ] 新功能提交
-   [x] bugfix
-   [ ] 组件样式改进
-   [ ] 代码风格优化
-   [ ] 重构
=> fix:Tree组件onRenameNode方法增加第三个参数

src/components/modal/demos/async.md, src/components/modal/demos/basic-modal.md, src/components/modal/demos/callback.md, src/components/modal/demos/component.md, src/components/modal/demos/confirm.md, src/components/modal/demos/conplex.md, src/components/modal/demos/defineInfoStyle.md, src/components/modal/demos/defineTpl.md, src/components/modal/demos/hasFooter.md, src/components/modal/demos/iframe-current.md, src/components/modal/demos/info.md, src/components/modal/demos/methodModal.md, src/components/modal/demos/nest.md, src/components/modal/demos/query.js, src/components/modal/demos/style.md, src/components/modal/index.js, src/components/modal/index.less, src/components/modal/index.md, src/components/modal/prompt.js
-   [x] 新功能提交
-   [ ] bugfix
-   [ ] 组件样式改进
-   [ ] 代码风格优化
-   [ ] 重构
=> [Modal] 新增showType区分iframe弹窗方式

src/components/tree/index.js, src/components/upload/index.js
-   [ ] 新功能提交
-   [x] bugfix
-   [ ] 组件样式改进
-   [ ] 代码风格优化
-   [ ] 重构
=> fix:upload组件unit属性优化

src/components/input-number/index.js
-   [ ] 新功能提交
-   [x] bugfix
-   [ ] 组件样式改进
-   [ ] 代码风格优化
-   [ ] 重构
=> input-number按钮更新问题

src/components/cascade/demos/moreCascade.md, src/components/cascade/index.js, src/components/cascade/index.md
-   [x] 新功能提交
-   [ ] bugfix
-   [ ] 组件样式改进
-   [ ] 代码风格优化
-   [ ] 重构
=> Feat cascade cop

src/components/form/demos/inline.md, src/components/form/index.less
-   [ ] 新功能提交
-   [ ] bugfix
-   [x] 组件样式改进
-   [ ] 代码风格优化
-   [ ] 重构
=> fix:Form inline模式样式问题

src/components/form/demos/inline.md, src/components/form/index.less, src/components/tabs/index.less
-   [ ] 新功能提交
-   [x] bugfix
-   [ ] 组件样式改进
-   [ ] 代码风格优化
-   [ ] 重构
=> Fixed tabs theme

src/components/tabs/index.js
-   [ ] 新功能提交
-   [x] bugfix
-   [ ] 组件样式改进
-   [ ] 代码风格优化
-   [ ] 重构
=> fixed: 修改选项卡样式

src/components/tree/index.js, src/components/tree/store.js
-   [ ] 新功能提交
-   [x] bugfix
-   [ ] 组件样式改进
-   [ ] 代码风格优化
-   [ ] 重构
=> fix: tree删除节点失败问题

src/components/tooltip/index.js
-   [ ] 新功能提交
-   [X] bugfix
-   [ ] 组件样式改进
-   [ ] 代码风格优化
-   [ ] 重构
- [Tooltip] 解决在火狐浏览器和mac台式机上tooltip点击内部区域异常关闭的问题(https://github.com/ShuyunFF2E/cloud-react/commit/52f3603fd4973b8358b85bdbe70f82b02c37653e)
- [Tooltip]解决tooltip偶发性位置计算错误的问题(https://github.com/ShuyunFF2E/cloud-react/commit/8610db9d87db4c11c941b9bc4636e9d723ef24be)
=> :bug: [Tooltip]解决在火狐浏览器和mac台式机上tooltip点击内部区域异常关闭的问题

src/components/form/demos/basic-forms.md, src/components/form/form-item.js, src/components/form/index.md, src/components/input-number/index.less, src/components/tooltip/index.js
-   [x] 新功能提交
-   [ ] bugfix
-   [ ] 组件样式改进
-   [ ] 代码风格优化
-   [ ] 重构
=> [Form]enhance:增加label description属性

src/components/radio/demos/group.md, src/components/radio/group.js, src/components/radio/index.md
-   [ ] 新功能提交
-   [x] bugfix
-   [ ] 组件样式改进
-   [ ] 代码风格优化
-   [ ] 重构
=> fix:RadioGroup修复嵌套问题

src/components/tree/const.js, src/components/tree/demos/basicSelector.md, src/components/tree/index.js, src/components/tree/index.md, src/components/tree/node.js, src/components/tree/store.js
-   [ ] 新功能提交
-   [ ] bugfix
1.[Tree] 节点新增支持传入ReactNode显示
2.[Tree] 数据中新增selectable定义
3.[Tree] 修复treeData发生改变时，组件没有重新渲染
=> [Tree] 新增参数/问题修复

package.json
-   [x] 新功能提交
-   [ ] bugfix
-   [ ] 组件样式改进
-   [ ] 代码风格优化
-   [ ] 重构
=> enhance: 增加changelog

src/components/icon/styles/icon.less
-   [ ] 新功能提交
-   [x] bugfix
-   [ ] 组件样式改进
-   [ ] 代码风格优化
-   [ ] 重构
=> fix:修复inputicon样式问题

src/components/icon/styles/icon.less, src/components/upload/constant.js
-   [ ] 新功能提交
-   [x] bugfix
-   [x] 组件样式改进
-   [ ] 代码风格优化
-   [ ] 重构
=> fix: upload组件icon优化

src/components/c-picker/pickers/date-range.js, src/components/c-picker/pickers/date.js, src/components/c-picker/pickers/time.js
-   [ ] 新功能提交
-   [x] bugfix
-   [ ] 组件样式改进
-   [ ] 代码风格优化
-   [ ] 重构
=> 修复时间选择器部分属性不生效的问题

src/components/upload/constant.js
-   [ ] 新功能提交
-   [ ] bugfix
-   [x] 组件样式改进
-   [ ] 代码风格优化
-   [ ] 重构
=> fix:upload icon优化

src/components/c-picker/pickers/date-range.js, src/components/c-picker/pickers/date.js, src/components/c-picker/pickers/time.js, src/components/complex-radio/index.js, src/components/field/demos/basic-forms.md, src/components/radio/group.js, src/components/radio/index.js, src/components/upload/constant.js
-   [ ] 新功能提交
-   [x] bugfix
-   [ ] 组件样式改进
-   [ ] 代码风格优化
-   [ ] 重构
=> fix:Radio文档站点点击无效

src/components/style/core/default.less
-   [ ] 新功能提交
-   [ ] bugfix
-   [ ] 组件样式改进
-   [ ] 代码风格优化
-   [ ] 重构
=> less prefix设置变量

.fatherrc.ts
-   [ ] 新功能提交
-   [ ] bugfix
-   [ ] 组件样式改进
-   [ ] 代码风格优化
-   [ ] 重构
=> 不用cdn的情况默认引入新的类

src/components/c-cascader/index.js, src/components/c-cascader/index.less
-   [ ] 新功能提交
-   [ ] bugfix
-   [ ] 组件样式改进
-   [ ] 代码风格优化
-   [ ] 重构
=> Bus dev rebase

.fatherrc.ts, src/components/select/index.js
-   [ ] 新功能提交
-   [x] bugfix
-   [x] 组件样式改进
-   [ ] 代码风格优化
-   [ ] 重构
=> fix:Select popup样式优化&打包问题修复

src/components/tree-select/demos/basic-tree-select.md, src/components/tree-select/demos/multiple.md, src/components/tree-select/index.js, src/components/tree-select/index.less, src/components/tree-select/selected.js, src/components/tree-select/single-tree.js, src/components/tree/index.less, src/components/tree/search.js
-   [ ] 新功能提交
-   [ ] bugfix
-   [x] 组件样式改进
-   [ ] 代码风格优化
-   [ ] 重构
=> feat:Tree selectUI修改

src/components/icon/index.js, src/components/index.js
-   [ ] 新功能提交
-   [x] bugfix
-   [ ] 组件样式改进
-   [ ] 代码风格优化
-   [ ] 重构
=> fix:[Icon]引入字体库时机修改

src/components/icon/index.js, src/utils/module.js
-   [ ] 新功能提交
-   [ ] bugfix
-   [ ] 组件样式改进
-   [ ] 代码风格优化
-   [ ] 重构
=> fix:Icon组件优化

src/components/c-picker/style/range.less
-   [ ] 新功能提交
-   [x] bugfix
-   [x] 组件样式改进
-   [ ] 代码风格优化
-   [ ] 重构
=> fix: 固定范围选择器下拉框

src/components/field/index.js, src/components/form/form-item.js, src/components/form/index.md
-   [x] 新功能提交
-   [ ] bugfix
-   [ ] 组件样式改进
-   [ ] 代码风格优化
-   [ ] 重构
=> feat:Form增加preserve属性

src/components/upload/demos/picture.md, src/components/upload/index.js, src/components/upload/index.md
-   [x] 新功能提交
-   [ ] bugfix
-   [ ] 组件样式改进
-   [ ] 代码风格优化
-   [ ] 重构
upload增加配置格式错误文件上传的提示信息
=> [upload]增加格式错误信息可配置

src/components/drawer/index.js, src/components/style/core/zindex.less
-   [ ] 新功能提交
-   [x] bugfix
-   [ ] 组件样式改进
-   [ ] 代码风格优化
-   [ ] 重构
=> [Drawer]抽屉问题修复

src/components/c-table/demos/checkbox.md, src/components/c-table/demos/front-table.md, src/components/c-table/demos/front-table1.md, src/components/c-table/demos/sort-front.md, src/components/c-table/demos/sort-store.md, src/components/c-table/demos/sort-with-page.md, src/components/c-table/index.js, src/components/c-table/index.md, src/components/c-table/js/column.js, src/components/c-table/js/propType.js, src/components/select/demos/basic.md, src/components/select/demos/unlimited.md, src/components/select/index.js, src/components/select/index.md, src/components/select/views/multi-select.js, src/components/select/views/option.js, src/components/select/views/selected.js
-   [X] 新功能提交
-   [X] bugfix
-   [ ] 组件样式改进
-   [ ] 代码风格优化
-   [ ] 重构
=> [CTable] 排序问题修复；新增 showCheckedAll 参数；[Select] 支持监听下拉选项disabled状态变化；多选下拉支持选择不限

src/components/select/demos/group.md, src/components/select/demos/group2.md, src/components/select/demos/groupSearch.md, src/components/select/index.js, src/components/select/index.less, src/components/select/index.md, src/components/select/utils.js, src/components/select/views/group-select.js, src/components/select/views/option.js
-   [x] 新功能提交
-   [ ] bugfix
-   [ ] 组件样式改进
-   [ ] 代码风格优化
-   [ ] 重构
地址选择器  支持分组展示店铺类型
=> 【下拉组件】分组功能

src/components/c-table/js/rowTooltip.js
-   [ ] 新功能提交
-   [x] bugfix
-   [ ] 组件样式改进
-   [ ] 代码风格优化
-   [ ] 重构
=> :bug: [CTable] 解决表格禁用行配置 tooltip 内容为空，tooltip 仍然展示的问题

src/components/c-table/css/basic.less, src/components/drawer/index.js, src/components/drawer/index.less, src/components/select/views/multi-select.js, src/components/style/core/normalize.less
-   [ ] 新功能提交
-   [ ] bugfix
-   [ ] 组件样式改进
-   [ ] 代码风格优化
-   [ ] 重构
=> [Drawer]抽屉添加动画[Select]解决多选下拉搜索关键字高亮失败的问题

src/components/pagination/index.js
-   [ ] 新功能提交
-   [x] bugfix
-   [ ] 组件样式改进
-   [ ] 代码风格优化
-   [ ] 重构
=> fix:修复分页输入0异常问题

src/components/c-picker/pickers/date-range.js, src/components/c-picker/pickers/date.js, src/components/c-picker/pickers/month.js, src/components/c-picker/pickers/quarter.js, src/components/c-picker/pickers/week.js, src/components/c-picker/pickers/year.js
-   [ ] 新功能提交
-   [x] bugfix
-   [ ] 组件样式改进
-   [ ] 代码风格优化
-   [ ] 重构
=> fix: 开始或结束时间为空时报错

src/components/c-table/js/rowTooltip.js
-   [ ] 新功能提交
-   [x] bugfix
-   [ ] 组件样式改进
-   [ ] 代码风格优化
-   [ ] 重构
=> [CTable]fix:表格行禁用时tooltip报错

src/components/select/index.js
-   [ ] 新功能提交
-   [ - ] bugfix 下拉分组回显问题
-   [ ] 组件样式改进
-   [ ] 代码风格优化
-   [ ] 重构
=> fixed[select] 下拉分组回显问题

src/components/c-table/index.js, src/components/modal/demos/confirm.md, src/components/modal/index.md, src/components/modal/prompt.js, src/components/tabs/demos/async.md, src/components/tabs/index.js, src/components/tabs/index.md
-   [X] 新功能提交
-   [X] bugfix
-   [ ] 组件样式改进
-   [ ] 代码风格优化
-   [ ] 重构
=> [CTable][Tabs]问题修改和功能新增

src/components/c-cascader/index.less
-   [ ] 新功能提交
-   [x] bugfix 【级联选择器】搜索文字颜色需要改成主色
-   [ ] 组件样式改进
-   [ ] 代码风格优化
-   [ ] 重构
=> 【级联选择器】搜索文字颜色需要改成主色

package.json, src/components/tabs/index.js
-   [ ] 新功能提交
-   [x] bugfix
-   [ ] 组件样式改进
-   [ ] 代码风格优化
-   [ ] 重构
=> 【tabs】更改activeEle没有时的报错

src/components/modal/prompt.js
-   [ ] 新功能提交
-   [ ] bugfix
-   [ ] 组件样式改进
-   [ ] 代码风格优化
-   [ ] 重构
=> :bug:解决在 modal 中使用 showConfirmLoading，加载失败，按钮仍然 loading ，无法再次操作的问题

src/components/input-number/demos/complex.md, src/components/input-number/index.js, src/components/input-number/index.less, src/components/input-number/index.md, src/components/input/demos/textarea.md, src/components/input/index.less, src/components/input/textarea.js
-   [ ] 新功能提交
-   [ ] bugfix
-   [ ] 组件样式改进
-   [ ] 代码风格优化
-   [ ] 重构
=> 【InputNumber】支持复合型输入框；[Input.Textarea]支持 resize 属性

package.json, src/components/c-table/demos/front-table.md, src/components/c-table/demos/lazyload.md, src/components/c-table/demos/light-click-row.md, src/components/c-table/demos/splitTable.md, src/components/c-table/demos/style/index.less, src/components/c-table/index.js, src/components/c-table/index.md, src/components/c-table/js/propType.js, src/components/modal/index.less
-   [ ] 新功能提交
-   [ ] bugfix
-   [ ] 组件样式改进
-   [ ] 代码风格优化
-   [ ] 重构
=> [CTable]添加rcTableConfig 参数，支持 rcTable API

src/components/c-table/columnTpl/link.js, src/components/c-table/columnTpl/multiLink.js, src/components/c-table/columnTpl/multiText.js, src/components/c-table/columnTpl/text.js, src/components/c-table/css/basic.less, src/components/c-table/css/business.less, src/components/c-table/demos/fixed-column.md, src/components/c-table/demos/uniform_text.md, src/components/c-table/demos/uniform_tpl.md, src/components/c-table/index.js, src/components/c-table/index.md, src/components/c-table/js/column.js
-   [ ] 新功能提交
-   [ ] bugfix
-   [ ] 组件样式改进
-   [ ] 代码风格优化
-   [ ] 重构
=> [CTable] 解决文字超长展示省略号的计算逻辑有误的问题

src/components/tree/store.js
-   [ ] 新功能提交
-   [ ] bugfix
-   [ ] 组件样式改进
-   [ ] 代码风格优化
-   [ ] 重构
=> fix: [Tree] 解决搜索节点，若匹配到的节点有多级，应全部展示，实际上只展示了匹配到节点的下一级的问题

src/components/modal/prompt.js
-   [ ] 新功能提交
-   [ ] bugfix
-   [ ] 组件样式改进
-   [ ] 代码风格优化
-   [ ] 重构
=> feat: [Modal] confirm添加外部footer样式属性

src/components/input-tag/index.js, src/components/input-tag/index.less, src/components/tooltip/demos/showArrow.md
-   [ ] 新功能提交
-   [ ] bugfix
-   [ ] 组件样式改进
-   [ ] 代码风格优化
-   [ ] 重构
=> inputTag适配主题色

src/components/icon/demos/icon-list.md, src/components/icon/styles/icon.less
-   [ ] 新功能提交
-   [ ] bugfix
-   [ ] 组件样式改进
-   [ ] 代码风格优化
-   [ ] 重构
=> feat: 新增图标

src/components/input-tag/index.js
-   [ ] 新功能提交
-   [ ] bugfix
-   [ ] 组件样式改进
-   [ ] 代码风格优化
-   [ ] 重构
=> feat: [inputTag] 修复赋值

src/components/c-table/js/columnConfig.js, src/components/index.js, src/components/popover/demos/basic.md, src/components/popover/index.js, src/components/popover/index.less, src/components/popover/index.md
=> Feat popover 0304

src/components/c-table/index.js, src/components/c-table/js/columnConfig.js
=> Feat ctable 0306

src/components/c-table/index.js
-   [ ] 新功能提交
-   [X] bugfix CTable右侧列固定不动， 样式异常问题
-   [ ] 组件样式改进
-   [ ] 代码风格优化
-   [ ] 重构
=> Fixed ctable joylee

src/components/c-table/index.js
-   [ ] 新功能提交
-   [X] bugfix
-   [ ] 组件样式改进
-   [ ] 代码风格优化
-   [ ] 重构
=> fix: 解决列固定阴影，偶发性不展示，滚动列才展示

package.json, src/components/index.js, src/components/slider/demos/basic.md, src/components/slider/demos/range.md, src/components/slider/index.js, src/components/slider/index.less, src/components/slider/index.md
-   [x] 新功能提交
-   [ ] bugfix
-   [ ] 组件样式改进
-   [ ] 代码风格优化
-   [ ] 重构
=> 增加组件：Slider

src/components/drawer/index.js
-   [ ] 新功能提交
-   [ ] bugfix
-   [ ] 组件样式改进
-   [ ] 代码风格优化
-   [ ] 重构
=> fix: [Drawer]解决抽屉更改 size 后，组件没有更新的问题
